### ISSUE TITLE
How can I get a list of available voices programatically?

### ISSUE THREAD

**Issue by bootrino** [Azure-Samples/Cognitive-Speech-TTS#100]
Could you please help me to get a list of available voices?

Ideally Python or curl

thanks!

**Comment by szhaomsft** [comment]
this API needs to be added

**Comment by szhaomsft** [comment]
@bootrino  added
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#get-a-list-of-voices
