### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by nmssalman** [Azure-Samples/Cognitive-Speech-TTS#103]
when i'm trying to run the project the following error raising.

Error = "The underlying connection was closed: An unexpected error occurred on a send."

Location:  1st line of below code

using (WebResponse webResponse = webRequest.GetResponse())
            {
                using (Stream stream = webResponse.GetResponseStream())
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        byte[] waveBytes = null;
                        int count = 0;
                        do
                        {
                            byte[] buf = new byte[1024];
                            count = stream.Read(buf, 0, 1024);
                            ms.Write(buf, 0, count);
                        } while (stream.CanRead && count > 0);

                        waveBytes = ms.ToArray();

                        return Encoding.UTF8.GetString(waveBytes);
                    }
                }
            }

**Comment by szhaomsft** [comment]
how to repo? @v-songl

**Comment by szhaomsft** [comment]
no responses
