### ISSUE TITLE
30-day free trial account can not use neural voices like "zh-CN-XiaoxiaoNeural"

### ISSUE THREAD

**Issue by GoTop** [Azure-Samples/Cognitive-Speech-TTS#109]
I signup a 30-day free trial account and use the key provided at https://azure.microsoft.com/zh-cn/try/cognitive-services/my-apis/ to run the python sample at https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/Python

when I use standard voices like "en-US-Jessa24kRUS", everything work fine.

but when I use neural voices like "zh-CN-XiaoxiaoNeural", it return status code: 400.
```
    def save_audio(self):
        base_url = 'https://westus.tts.speech.microsoft.com/'
        path = 'cognitiveservices/v1'
        constructed_url = base_url + path
        headers = {
            'Authorization': 'Bearer ' + self.access_token,
            'Content-Type': 'application/ssml+xml',
            'X-Microsoft-OutputFormat': 'riff-24khz-16bit-mono-pcm',
            'User-Agent': 'YOUR_RESOURCE_NAME'
        }
        body = '''<speak version='1.0' xmlns="https://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="zh-CN">
<voice name='zh-CN-XiaoxiaoNeural'>
    ElementTree是Python常用的处理XML文件的类。下面将介绍使用ElementTree解析、查找、修改XML的方法。
</voice></speak>'''.encode('utf-8')
        '''
        If a success response is returned, then the binary audio is written
        to file in your working directory. It is prefaced by sample and
        includes the date.
        '''
        if response.status_code == 200:
            with open('sample-' + self.timestr + '.wav', 'wb') as audio:
                audio.write(response.content)
                print("\nStatus code: " + str(
                    response.status_code) + "\nYour TTS is ready for playback.\n")
        else:
            print("\nStatus code: " + str(response.status_code)
                  + "\nReason: " + str(response.reason)
                  + "\nSomething went wrong. Check your " \
                    "subscription key and headers.\n")
```
in the console, it show:
'Unsupported voice Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoNeural).'

**Comment by boltomli** [comment]
zh-CN-HuihuiRUS is also standard voice. Let me check the status.

**Comment by GoTop** [comment]
> zh-CN-HuihuiRUS is also standard voice. Let me check the status.

sorry, it should be "zh-CN-XiaoxiaoNeural", i had corrected my question.

**Comment by GoTop** [comment]
I had figure it out:
as a 30-day free trial account, I have to use Endpoint: https://westus.api.cognitive.microsoft.com/sts/v1.0
but this endpoint belong to West US Region, which doesn't suport Neural Voices according to this info:
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/regions#standard-and-neural-voices

That mean, a 30-day free trial account can not test  Neural Voices.

**Comment by boltomli** [comment]
Yes, I think you're right. "zh-CN-XiaoxiaoNeural" is available on southeastasia endpoint only so far.
