### ISSUE TITLE
If the first token acquisition fails

### ISSUE THREAD

**Issue by shaohui93** [Azure-Samples/Cognitive-Speech-TTS#115]
If the first acquisition of token fails, it will take 9 minutes before the second acquisition, and after 9 minutes all speech synthesis will fail.

**Comment by shaohui93** [comment]
All speech synthesis fails in nine minutes

**Comment by boltomli** [comment]
Thanks for the question. I'll check at my side.

**Comment by boltomli** [comment]
Did you retry the wrong key a lot in a short period? It may trigger limitation. Perhaps you should avoid retrying too much in your code if the request fails.

**Comment by shaohui93** [comment]
I mean, if the first time you use Authentication to get token fails, it takes nine minutes to get token again. So token is invalid when using this kind of synthesizer to synthesize speech in 9 minutes because it failed to get token by using Authentication, and it must be retrieved after 9 minutes. Will this result in all speech synthesis failures in 9 minutes?

**Comment by boltomli** [comment]
It might be related to the implementation detail. Reuse a new connection to get token can be done right after your first failure. Don't have to wait. Limit will still trigger, however, if you fail too fast for many times.

**Comment by shaohui93** [comment]
Okay, I see.
