### ISSUE TITLE
Does the body of request post method in the sever endpoint have a  limited length? When I use many kinds of voices to synthesize a dialogue,something went wrong: StatusCodeError: 400 - ""

### ISSUE THREAD

**Issue by DerrickYang007** [Azure-Samples/Cognitive-Speech-TTS#118]
### **The code:**
`function textToSpeech(accessToken, text) {
       let body = ''; 
	var  neauralFemale = 'en-US-JessaNeural'
	var  neauralMale = 'en-US-GuyNeural'
	var delayTime = '500ms'

	  var xml_body2 = xmlbuilder.create('speak')
	    .att('version', '1.0')
		.att('xmlns','https://www.w3.org/2001/10/synthesis')
		.att('xmlns:mstts','https://www.w3.org/2001/mstts')
        .att('xml:lang', 'en-us');

var textArray=new Array()
	textArray[0]='Something wrong?'
	textArray[1]='Yes. My car is having problems.'
	textArray[2]='What\'s wrong?'
	textArray[3]='It won\'t start.'
	textArray[4]='Do you want me to take a look?'
	textArray[5]='No,thank you. I think I can handle it.'
	textArray[6]='Well, if you change your mind, let me know.'
	textArray[7]='I will. Thanks. That\'s sweet of you.'
	textArray[8]='No problem.'
	textArray[9]='I might need some tools though. Do you know where I can get some?'
	textArray[10]='Sure. I have all kinds of tools. Just ask. I\'ll be happy to get them for you.'
	textArray[11]='Thanks. That would be very helpful.'
	textArray[12]='Anything for you. Seriously, I don\'t mind helping.'
	textArray[13]='OK. If you really insist, I could always use the company.'

		for(i=0;i<textArray.length;i++){
		if((i%2 == 0)){
		 xml_body2.ele('voice')
        .att('xml:lang', 'en-us')
        .att('name', neauralFemale)
		.ele('mstts:express-as')
		.att('type','empathy')
		.ele('prosody')
        .att('rate', '1')
        .att('volume', '100.0')
        .txt(textArray[i])
		.ele('break')
		.att('time','500ms');
			}else{
		 xml_body2.ele('voice')
        .att('xml:lang', 'en-us')
        .att('name', neauralMale)
        .txt(textArray[i])
		.ele('break')
		.att('time','500ms');
			}	
		}
var xml = xml_body2.end({ pretty: true});

	 body = xml.toString();
	 
console.log('body='+body)

    let options = {
        method: 'POST',
        baseUrl: BaseUrl,
        url: 'cognitiveservices/v1',
        headers: {
            'Authorization': 'Bearer ' + accessToken,
            'cache-control': 'no-cache',
            'User-Agent': 'YOUR_RESOURCE_NAME',
            'X-Microsoft-OutputFormat':OutputFormat,
            'Content-Type': 'application/ssml+xml'
        },
        body: body
    }

   let request = rp(options)
        .on('response', (response) => {
            if (response.statusCode === 200) {
                request.pipe(fs.createWriteStream('finalvoice'+'.mp3'));
                console.log('\nYour file is ready.\n')
            }
        });
		
    return request;
}``

###  **Reslut:**

Something went wrong: StatusCodeError: 400 - ""

but when I reduce the text items of the textArray to 
       textArray[0]='Something wrong?'
	textArray[1]='Yes. My car is having problems.'
	textArray[2]='What\'s wrong?'
	textArray[3]='It won\'t start.'
	textArray[4]='Do you want me to take a look?'

then  it's ok. The code can be executed correctly.

I have checked the form of  my Speech Synthesis Markup Language (SSML),
It's right.  
So ,I surmise that the https post  request has limited length about body parameter in the server endpoint.
Am I right? How can I resolve the issue?

Some friends can help me?

### **Summarized：**
Target:
I want to generate a long dialogue script's  neaural voice.
When it is a short dialogue script,the neaural voice can generated correctly ,but if  it is a long dialogue script, there is a problem.
The error message is   
Something went wrong: StatusCodeError: 400 - ""

**Comment by DerrickYang007** [comment]
body=<?xml version="1.0"?>
<speak version="1.0" xmlns="https://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="en-us">
  <voice xml:lang="en-us" name="en-US-JessaNeural">
    <mstts:express-as type="empathy">
      <prosody rate="1" volume="100.0">
        Something wrong?
        <break time="500ms"/>
      </prosody>
    </mstts:express-as>
  </voice>
  <voice xml:lang="en-us" name="en-US-GuyNeural">
    Yes. My car is having problems.
    <break time="500ms"/>
  </voice>
  <voice xml:lang="en-us" name="en-US-JessaNeural">
    <mstts:express-as type="empathy">
      <prosody rate="1" volume="100.0">
        What's wrong?
        <break time="500ms"/>
      </prosody>
    </mstts:express-as>
  </voice>
  <voice xml:lang="en-us" name="en-US-GuyNeural">
    It won't start.
    <break time="500ms"/>
  </voice>
  <voice xml:lang="en-us" name="en-US-JessaNeural">
    <mstts:express-as type="empathy">
      <prosody rate="1" volume="100.0">
        Do you want me to take a look?
        <break time="500ms"/>
      </prosody>
    </mstts:express-as>
  </voice>
  <voice xml:lang="en-us" name="en-US-GuyNeural">
    No,thank you. I think I can handle it.
    <break time="500ms"/>
  </voice>
</speak>
Something went wrong: StatusCodeError: 400 - ""

**Comment by DerrickYang007** [comment]
I have tested many times.

**Comment by boltomli** [comment]
For this kind of request, I believe there's a batch API to use, that can generate synthesis in a batch. @xiaozhouz had some examples in https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/CustomVoice-API-Samples

**Comment by yulin-li** [comment]
Hi @DerrickYang007 The failure is because the server endpoint has a limit for vice elements in a single SSML of 5, while your example has 6 elements.

The server gives a short error detail in [Reason Phrase](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html), you can log this information to help your  diagnosis.
