### ISSUE TITLE
NodeJS - 400 error

### ISSUE THREAD

**Issue by netRunner0** [Azure-Samples/Cognitive-Speech-TTS#138]
Hi
I get this error when I use the provided example TTSSample.js  for a node.

My key was received for 30 days and the entry point for it is Westus.

`pi@raspberrypi:~ $ node TTSSample.js
What would you like to convert to speech? hello
Something went wrong: StatusCodeError: 400 - "<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0aFp7XQAAAACO+qFxcupwQLxb/PcYN9qFU1RPRURHRTEwMTkARWRnZQ=="
`

**Comment by boltomli** [comment]
Does it still reproduce? It might be a temporary accident.
