### ISSUE TITLE
php tts is not working .

### ISSUE THREAD

**Issue by ravi145bittu** [Azure-Samples/Cognitive-Speech-TTS#145]
i am new in this i tried all possible way to solve the issue but it's not working . as the read md file suggest i change $AccessTokenUri  and $apiKey according to token key that i have create in azure  . but  sound or (speak)  is not working for me . but the wave data is showing .

here what my web page is showing .
Access Token: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJleHAiOiIxNTcxODI4MDEzIiwicmVnaW9uIjoiZWFzdHVzIiwic3Vic2NyaXB0aW9uLWlkIjoiNWM1Y2E5ZWJhMTUxNGEzMjg3YWI1Y2I1ZjQzM2ZkNDEiLCJwcm9kdWN0LWlkIjoiU3BlZWNoU2VydmljZXMuRjAiLCJjb2duaXRpdmUtc2VydmljZXMtZW5kcG9pbnQiOiJodHRwczovL2FwaS5jb2duaXRpdmUubWljcm9zb2Z0LmNvbS9pbnRlcm5hbC92MS4wLyIsImF6dXJlLXJlc291cmNlLWlkIjoiL3N1YnNjcmlwdGlvbnMvZmVhZjk0YmItMGRiYi00MWE3LWFjNTYtYzc3OWNmZGUyODE5L3Jlc291cmNlR3JvdXBzL1BHL3Byb3ZpZGVycy9NaWNyb3NvZnQuQ29nbml0aXZlU2VydmljZXMvYWNjb3VudHMvcGdfbmV1cmFsIiwic2NvcGUiOiJzcGVlY2hzZXJ2aWNlcyIsImF1ZCI6InVybjptcy5zcGVlY2hzZXJ2aWNlcy5lYXN0dXMifQ.Jmtf6qtthhc6dkF-FyaDI-BKUPrP7bW3XuBLLF68QYo
tts post data: This is a demo to call microsoft text to speech service in php. hi how r u
Wave data length: 288900

**Comment by boltomli** [comment]
The data length looks good, so it seems you already get the code and key working :)

**Comment by ravi145bittu** [comment]
but it is not producing sound

**Comment by boltomli** [comment]
Did you check content of the `$result`? It should be the data you need to play back. The format is defined in header. You can either save the data as file to listen or play it as a stream, I think. It's not part of the API usage.

**Comment by ravi145bittu** [comment]
i checked the content of result it is wave format like something but i not able to stream or save the audio can you help in that

**Comment by boltomli** [comment]
Sorry I can't help without your code, and it's not part of the simple sample. You might try some forum such as stackoverflow. Or if you have an open source repo/code, someone might take a look in case.
