### ISSUE TITLE
MRCP Sample: Recognition done only once

### ISSUE THREAD

**Issue by scott-lang** [Azure-Samples/Cognitive-Speech-TTS#160]
I am able to run this project end to end on a freeswitch unimrcp stack, the only issue I am facing is that the recognizer is able to recognize the user input only once after that recognition does not take place neither the other code steps get executed.

Please let me know if this issue is occurring only with me or it is a know issue.

Thanks

**Comment by szhaomsft** [comment]
@yulin-li  can u take a look?

**Comment by yulin-li** [comment]
Hi @scott-lang , thanks for reaching out.
The recog plugin here is intended to run only once. In a call, the recog plugin receives audio and detects the finish signal of the audio, then returns the recognized test.

Could you decribe you scenario in more detail? Maybe we can give some advices.

**Comment by scott-lang** [comment]
Hi @yulin-li the scenario is I am writing a script using microsoft tts and stt, the job of the script as of now is to just repeat what the user has said , I am using the `lua` script attached below to fullfil this purpose, 

`--freeswitch.consoleLog("INFO", "Called extension is '".. argv[1]"'\n")
welcome = "ivr/ivr-welcome_to_freeswitch.wav"
menu = "ivr/ivr-this_ivr_will_let_you_test_features.wav"
--
grammar = "hello"
no_input_timeout = 80000
recognition_timeout = 80000
confidence_threshold = 0.2
--
session:streamFile(welcome)
--freeswitch.consoleLog("INFO", "Prompt file is \n")
tryagain = 1
session:set_tts_params("unimrcp", "jessie");
while (session:ready() == true and tryagain == 1) do

        freeswitch.consoleLog("CRIT","SPEAKING");

       session:execute("play_and_detect_speech",menu .. "detect:unimrcp {start-input-timers=false,no-input-timeout=" .. no_input_timeout .. ",recognition-timeout=" .. recognition_timeout .. "}builtin:grammar/transcribe")
      xml = session:getVariable('detect_speech_result')
       if (xml == nil) then
             freeswitch.consoleLog("CRIT","Result is 'nil'\n")
             tryagain = 0
      else
             freeswitch.consoleLog("CRIT","Result is '" .. xml .. "'\n")
             session:speak("hello world");
             tryagain = 1
   end
end
 --
 -- put logic to forward call here
 --
session:sleep(250)
session:speak("Disconnecting the call");
 session:hangup()
`
On executing the script when control goes first time into the loop it gets executed as expected  and I get the result in xml variable but the second time when the control goes into the loop the second time menu gets played as expected but now the recognition does not take place and neither I get any result in the xml variable.

I have tried to explain the problem clearly, please let me know if you find any issues in the script of if you have a sample script the you can give me so I can proceed.
Thanks

**Comment by yulin-li** [comment]
Hi @scott-lang 

I repro your issue and give a fix in #162 , you can try it after merged.
Thanks angin for point out this bug.

**Comment by scott-lang** [comment]
@yulin-li thank you so much I will check and let you know.

**Comment by Thilip707** [comment]
using the above code it detects only hello , how to use it pls guide me to get out of this issue
