### ISSUE TITLE
voiceclient.py sample code issue

### ISSUE THREAD

**Issue by jinyugang** [Azure-Samples/Cognitive-Speech-TTS#169]
when I just run the sample code voiceclient.py.  I met below issue
input:
```
python voiceclient.py --submit -region eastus -key XXXXXXXXXXXXX -file en-US.txt -locale en-US -voiceId en-US-AriaRUS -format riff-8khz-16bit-mono-pcm --concatenateResult
```
output:
```
Submit synthesis request failed
response.status_code: 400
response.text: {"Code":"InvalidRequest","Details":null,"Message":"The voice synthesis definition has the wrong format.","Target":null,"InnerError":{"Code":"InvalidPayload","Details":null,"Message":"The voice synthesis definition has the wrong format.","Target":null,"InnerError":null}}
```
pls help let me know how to fix that... 

Updated a little for better view.

**Comment by boltomli** [comment]
What is your result of `--voices`? I think this client sample is for custom voice, which you created yourself, but not the publicly served voices such as Aria.

**Comment by yeyuan-huang** [comment]
Perhaps you can replace paramter "-voiceid" from " en-US-AriaRUS" to an valid ID(guid) .
for voiceid , please try excute: python voiceclient.py ----voices -region eastus -key XXXXXXXXXXXXX.. to get the usable voices in this region.  region could be centralindia, canadacentral or uksouth

**Comment by yeyuan-huang** [comment]
> when I just run the sample code voiceclient.py. I met below issue
> input:
> 
> ```
> python voiceclient.py --submit -region eastus -key XXXXXXXXXXXXX -file en-US.txt -locale en-US -voiceId en-US-AriaRUS -format riff-8khz-16bit-mono-pcm --concatenateResult
> ```
> 
> output:
> 
> ```
> Submit synthesis request failed
> response.status_code: 400
> response.text: {"Code":"InvalidRequest","Details":null,"Message":"The voice synthesis definition has the wrong format.","Target":null,"InnerError":{"Code":"InvalidPayload","Details":null,"Message":"The voice synthesis definition has the wrong format.","Target":null,"InnerError":null}}
> ```
> 
> pls help let me know how to fix that...
> 
> Updated a little for better view.

Perhaps you can replace paramter "-voiceid" from " en-US-AriaRUS" to an valid ID(guid) .
for voiceid , please try excute: python voiceclient.py ----voices -region eastus -key XXXXXXXXXXXXX.. to get the usable voices in this region. region could be centralindia, canadacentral or uksouth

**Comment by xiaozhouz** [comment]
Today you probably won't see any voice by calling "--voice" because it only support custom neural voice today. 

We plan to release public neural voice in May. Please stay tuned.

**Comment by jinyugang** [comment]
I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis

**Comment by jinyugang** [comment]
> Today you probably won't see any voice by calling "--voice" because it only support custom neural voice today.
> We plan to release public neural voice in May. Please stay tuned.

so long audio API only for customized voice now... can you help give me a trigger how to use long audio API for public voice now...

**Comment by boltomli** [comment]
> I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis

So far there's a note:

![image](https://user-images.githubusercontent.com/5236916/81665320-27e9b900-9473-11ea-801c-0b45745a22a6.png)

Stay tuned, as we will update the document and [announce](https://github.com/Azure-Samples/Cognitive-Speech-TTS/wiki) when new feature is enabled.

**Comment by jinyugang** [comment]
> I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> 
> So far there's a note:
> 
> Stay tuned, as we will update the document and announce when new feature is enabled.

okey. got it...

**Comment by xiaozhouz** [comment]
> > I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> > So far there's a note:
> > Stay tuned, as we will update the document and announce when new feature is enabled.
> 
> okey. got it...

Just want to understand your requirement: why you want to call long audio api? We have realtime api which already support 5 public neural voice, and it is cheaper than long audio api.

**Comment by jinyugang** [comment]
> I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> So far there's a note:
> Stay tuned, as we will update the document and announce when new feature is enabled.
> 
> okey. got it...
> 
> Just want to understand your requirement: why you want to call long audio api? We have realtime api which already support 5 public neural voice, and it is cheaper than long audio api.

actually we wanna use SSML feature. but it need submit a document. so then we goes here to try long audio api...  if there its other way can do this. pls give me a coach.

**Comment by xiaozhouz** [comment]
> > I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> > So far there's a note:
> > Stay tuned, as we will update the document and announce when new feature is enabled.
> > okey. got it...
> > Just want to understand your requirement: why you want to call long audio api? We have realtime api which already support 5 public neural voice, and it is cheaper than long audio api.
> 
> actually we wanna use SSML feature. but it need submit a document. so then we goes here to try long audio api... if there its other way can do this. pls give me a coach.

realtime api support ssml. here is the doc: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#sample-request-1

**Comment by jinyugang** [comment]
> I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> So far there's a note:
> Stay tuned, as we will update the document and announce when new feature is enabled.
> okey. got it...
> Just want to understand your requirement: why you want to call long audio api? We have realtime api which already support 5 public neural voice, and it is cheaper than long audio api.
> 
> actually we wanna use SSML feature. but it need submit a document. so then we goes here to try long audio api... if there its other way can do this. pls give me a coach.
> 
> realtime api support ssml. here is the doc: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#sample-request-1

Tks. I already use this API to convert lot of text to wav yet.  the sample code its a simple input way which I can copy/paste the wording which wanna transfer to voice.  but the questions its how can I give this API a txt which already have the SSML format... can you show me a script which can done this . best regard first.

**Comment by xiaozhouz** [comment]
> > I download the code from this web page recommendation. which its long tone API which allow submit a document... I am not sure that's just for customized voice or public voice...https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api#prepare-content-for-synthesis
> > So far there's a note:
> > Stay tuned, as we will update the document and announce when new feature is enabled.
> > okey. got it...
> > Just want to understand your requirement: why you want to call long audio api? We have realtime api which already support 5 public neural voice, and it is cheaper than long audio api.
> > actually we wanna use SSML feature. but it need submit a document. so then we goes here to try long audio api... if there its other way can do this. pls give me a coach.
> > realtime api support ssml. here is the doc: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#sample-request-1
> 
> Tks. I already use this API to convert lot of text to wav yet. the sample code its a simple input way which I can copy/paste the wording which wanna transfer to voice. but the questions its how can I give this API a txt which already have the SSML format... can you show me a script which can done this . best regard first.

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/Python/TTSSample.py  
This sample construct the ssml dynamically. You can easily change it to use a ssml you already have. Just replace line 63 " body = ElementTree.tostring(xml_body)" with " body = <your ssml string>"
