### ISSUE TITLE
Pitch contour on neural voices with style

### ISSUE THREAD

**Issue by johnwood-wff** [Azure-Samples/Cognitive-Speech-TTS#186]
The documentation says that prosody pitch contours now work for neural voices. However I'm not able to get it to work. I'm trying this:

`<speak version="1.0" xml:lang="en-US"><voice xml:lang="en-US" xml:gender="Female" xmlns:mstts='https://www.w3.org/2001/mstts' name="En-US-AriaNeural"><mstts:express-as type="customerservice"><prosody contour="(0%,-2st) (17%,-2st) (33%,+0st) (50%,+3st) (67%,+3st) (83%,+3st) ">What is the Security Policy</prosody></mstts:express-as></voice></speak>`

...but it doesn't seem to be having any effect. Any idea why?

Thanks,
John

**Comment by johnwood-wff** [comment]
Actually it seems to break when I put in the express-as customerservice... if I take that out, then it does seem to have an impact on pitch. Is it not supported with different voice expressions?

**Comment by boltomli** [comment]
I think you refer to the updated document [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#change-pitch-contour). Style and manual prosody may interfere with each other and the result is not expected. Let me check.

**Comment by johnwood-wff** [comment]
Yes I was referring to the updated documentation. Was quite excited when I read it! Unfortunately it seems that it doesn't work with my custom voice data either :(

**Comment by boltomli** [comment]
Can you try larger values if it doesn't sound different obviously? It is more clear, for example `<prosody contour="(0%,-20st) (17%,-20st) (33%,+0st) (50%,+70st) (67%,+70st) (83%,+70st)">What is the Security Policy</prosody>`

Perhaps you need larger values to use with styles.

**Comment by szhaomsft** [comment]
which voice do you use?

**Comment by johnwood-wff** [comment]
I did get it to kind of work, albeit unreliably, with much larger values. I was testing this with a custom voice, but also with zh-CN-XiaoxiaoNeural and en-US-AriaNeural.

**Comment by johnwood-wff** [comment]
It would be more reliable IMO if you could apply it to a series of words, instead of being forced to apply it only to a sentence. The percentages are too hard to match up when it comes to long sentences, because you don't know the speed that certain words are pronounced. Is it possible to allow it to be applied per word?
