### ISSUE TITLE
Unable to get LongAudio to work

### ISSUE THREAD

**Issue by RSkoon** [Azure-Samples/Cognitive-Speech-TTS#188]
I am trying to incorporate support for LongAudio into a UWP project and it is not working.  I tried just get the CustomVoice C# API sample and that isn't working either...

If I build it w/o modification and then try to submit, I can't seem to figure out what the HostURI should be.   I have tried the various permutations listed in the docs (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#speech-to-text-text-to-speech-and-translation) as well as here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/long-audio-api and they all give me a "Not Found" error.  

I can submit to the service using the region specified in the usage text (https://eastus.cris.ai/) with my key although I don't suspect it should actually go here, TBH, I didn't actually expect it to work either.  However, this doesn't actually seem to do any processing of the job, as it just stays in a "Not Started" state, and I am not able to delete it by Id (saying it is in use)

I can use the Azure Speech SDK, but that doesn't seem to have support for the LongAudio

Definitely a bit frustrating here...   Ideas?

**Comment by fermatrix91** [comment]
Does this api support more than 10 minutes, right? 

I receive this message with long text:

 _**TaskCanceledException: A task was canceled.**_
