### ISSUE TITLE
Changing pitch in PHP

### ISSUE THREAD

**Issue by FreddyCrugger** [Azure-Samples/Cognitive-Speech-TTS#191]
Hello,

I would like to know if there is a way to change the pitch from the PHP side.
I tried this:
```
            $pitch = $doc->createElement("prosody");
            $pitch->setAttribute("pitch", "x-high");
//or      $pitch->setAttribute("pitch", 1.2);

            $text = $doc->createTextNode($text);

            $voice->appendChild($text);
            $pitch->appendChild($voice);
            $root->appendChild($voice);
            $doc->appendChild($root);
```

Unfortunately without luck.

Any idea why this is not working please?

Thank you.

**Comment by boltomli** [comment]
As noted in the [SSML document](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#change-pitch), the order would be voice->pitch->text, like:

```php
            $pitch->appendChild($text);
            $voice->appendChild($pitch);
```

**Comment by FreddyCrugger** [comment]
Thanks, this is the confusing part as the example shows this:
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US">
    <voice name="en-US-Guy24kRUS">
        Welcome to <prosody pitch="high">Microsoft Cognitive Services Text-to-Speech API.</prosody>
    </voice>
</speak>

The order here is:
Speak->Voice->Text->Prosody->Pitch

So something like this should work:
```
            //Speak
            $root = $doc->createElement("speak");
            $root->setAttribute("version", "1.0");
            $root->setAttribute("xml:lang", "en-us");
```

```
           //Voice
           $voice = $doc->createElement("voice");
           $voice->setAttribute("xml:lang", "en-US");
           $voice->setAttribute("xml:gender", "Female");
           $voice->setAttribute("name", "en-US-AriaNeural");
```

```
           //Text
          $text = $doc->createTextNode($text);
```

```
          //Prosody(If I want the pitch to change on the entire text).
          $pitch = $doc->createElement("prosody");
```
            
```
         //Pitch
          $pitch->setAttribute("pitch", 0.5);
```

          
```
          //Not sure about the last part.
            $pitch->appendChild($text);
            $voice->appendChild($pitch);
            $root->appendChild($voice);
            $doc->appendChild($root);
            $data = $doc->saveXML();
```


With this order I am getting:

```
message: "file_get_contents(https://westeurope.tts.speech.microsoft.com/cognitiveservices/v1): failed to open stream: HTTP request failed! HTTP/1.1 400 Synthesis failed. StatusCode: FailedPrecondition, Details: SSML parsing error: 80045003.
↵"
```

**Comment by FreddyCrugger** [comment]
Ok Got it,
It only takes a string:
$pitch->setAttribute("pitch", "high");

I thought I could have changed it with a decimal like:
$pitch->setAttribute("pitch", 0.5);

**Comment by boltomli** [comment]
Exactly. The sample here actually contains two parts, `Welcome to` and `Microsoft Cognitive Services Text-to-Speech API.`, with only the latter surrounded in prosody tag.

Regarding `0.5`, that is parsed as SSML (which is kind of XML), the attribute should be a string. The Hz convention might be "+80Hz" without space. I'll take a look at the document and update.

> Thanks, this is the confusing part as the example shows this:
> 
> ```
> <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US">
>     <voice name="en-US-Guy24kRUS">
>         Welcome to <prosody pitch="high">Microsoft Cognitive Services Text-to-Speech API.</prosody>
>     </voice>
> </speak>
> ```

**Comment by FreddyCrugger** [comment]
Yes you are right, I tried this +80Hz and it worked, the spacing in the doc was the issue.

Thanks again.
