### ISSUE TITLE
Not sure how to handle a break

### ISSUE THREAD

**Issue by FreddyCrugger** [Azure-Samples/Cognitive-Speech-TTS#192]
Hello,

I would like to know what is the best way to handle a `<break time="2s" />`.
If I add it to my text, the voice reads it "as is"(as words but not a pause).

This is my output from `$data = $doc->saveXML(); `

I believe the attributes are correctly set as the doc suggest here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#create-an-ssml-document
```
            $root = $doc->createElement("speak");
            $root->setAttribute("version", "1.0");
            $root->setAttribute("xml:lang", "en-us");
            $root->setAttribute("xmlns", "http://www.w3.org/2001/10/synthesis");

```
```
<?xml version="1.0"?>
<speak version="1.0" xml:lang="en-us">
<voice xml:lang="en-US" xml:gender="Female" name="en-US-AriaNeural">
<prosody pitch="+1st">Convert Text to Voice&lt;break time="2s"/&gt; the pause should be here.</prosody>
</voice>
</speak>
```

Thank you.

**Comment by boltomli** [comment]
The SSML should look like

```xml
<?xml version="1.0"?>
<speak version="1.0" xml:lang="en-us">
<voice xml:lang="en-US" xml:gender="Female" name="en-US-AriaNeural">
<prosody pitch="+1st">Convert Text to Voice<break time="2s"> the pause should be here.</prosody>
</voice>
</speak>
```

The break tag is encoded in your example, which is not working properly. Here's part of my attempt:

```php
   $text1 = $doc->createTextNode( "Convert Text to Voice" );
   $break = $doc->createElement( "break" );
   $break->setAttribute( "time", "2s" );
   $text2 = $doc->createTextNode( "the pause should be here." );
   $prosody->appendChild( $text1 );
   $prosody->appendChild( $break );
   $prosody->appendChild( $text2 );
```

**Comment by FreddyCrugger** [comment]
Thank you for the reply.

So I have found the problem.
In your PHP sample on GitHub you use this(Line 57):

`$text = $doc->createTextNode($text);`

`https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/PHP/TTSService.php`

But from what I understand:
`https://www.php.net/manual/en/domdocument.createtextnode.php`

This method changes the characters into character entities like  &lt;break time="2s"/&gt;  .


Which would explain why if I have this:
$text = "<?xml version="1.0"?>
<speak version="1.0" xml:lang="en-us">
<voice xml:lang="en-US" xml:gender="Female" name="en-US-AriaNeural">
<prosody pitch="+1st">Convert Text to Voice<break time="2s"> the pause should be here.</prosody>
</voice>
</speak>";


It will become:
$text = "<?xml version="1.0"?>
<speak version="1.0" xml:lang="en-us">
<voice xml:lang="en-US" xml:gender="Female" name="en-US-AriaNeural">
<prosody pitch="+1st">Convert Text to Voice&lt;break time="2s"/&gt; the pause should be here.</prosody>
</voice>
</speak>";



When you do this:
```
  $text1 = $doc->createTextNode( "Convert Text to Voice" );
   $break = $doc->createElement( "break" );
   $break->setAttribute( "time", "2s" );
   $text2 = $doc->createTextNode( "the pause should be here." );
   $prosody->appendChild( $text1 );
   $prosody->appendChild( $break );
   $prosody->appendChild( $text2 );
```

Yes it works, but the problem is  that if you have a panel with drag and drop(HTML panel) and the user adds a break into the text itself, you need to pass the entire text as "Convert Text to Voice<break time="2s"> the pause should be here." into  `$text = $doc->createTextNode($text);`

Shall I simply remove:
`$text = $doc->createTextNode($text);`

And add it directly as:
```
            $pitch->appendChild($text);  <-------------(without creating a a Text Node?)
            $voice->appendChild($pitch);
            $root->appendChild($voice);
            $doc->appendChild($root);

```

Thank you,

**Comment by boltomli** [comment]
It depends on your overall design of the web page frontend how to achieve the goal to insert break to text. Just make sure it's safe before appending user input to text directly. Text node is more safe (but I guess you'll still want to have some checks in case). The method you use should work for simple usage I think.

**Comment by FreddyCrugger** [comment]
Thank you so much.
I think I now have enough information to move forward with it :-)  Thank you so much for your great help!
I will not use createTextNode($text) but another function as this one escape the characters(Some people are warning others about it on the PHP function page of php.net).

I will now close the comments, thank you much!
