### ISSUE TITLE
Neural voices do not work 

### ISSUE THREAD

**Issue by marlon-br** [Azure-Samples/Cognitive-Speech-TTS#193]
Hi, 

I use python and TranslationRecognizer to recognize, translate and synthesize. All works OK for standard voices, but for neural voices I get error: 
`Audio cancelled: CancellationDetails(reason=CancellationReason.Error, error_details="Synthesis service failed with code:  - Could not identify the voice 'en-US-AriaNeural' for the text to speech service ...`

This is for 'eastus' region, so I expect it should support neural voices. Any ideas why that happens?

**Comment by boltomli** [comment]
I used 'eastus' region with the voice name 'en-US-AriaNeural' in the minimal Python code sample, it works well.

**Comment by marlon-br** [comment]
Please show your code. It does not work on my side and I want to understand why it happens

**Comment by boltomli** [comment]
I refer to the very simple code in this repo <https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/Python>.

Your error could be speech SDK problem (which is in <https://github.com/Azure-Samples/cognitive-services-speech-sdk>) but I'm not sure. Perhaps you can try use the basic https post and see if the same issue happens.

**Comment by marlon-br** [comment]
If I use sample code from https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-translation 
I have got the same result. "de-DE-Hedda" works, "en-US-AriaNeural" does not work. 
To understand that I add:
```
def cancelled_callback(evt):
    print(f'Audio cancelled: {evt.cancellation_details}')

recognizer.canceled.connect(cancelled_callback)
```
into the code

**Comment by marlon-br** [comment]
> I refer to the very simple code in this repo https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/Python.
> 
> Your error could be speech SDK problem (which is in https://github.com/Azure-Samples/cognitive-services-speech-sdk) but I'm not sure. Perhaps you can try use the basic https post and see if the same issue happens.

I tried the sample you mentioned and it works for the required voices.
