### ISSUE TITLE
What is the plan to have pronunciation assessment in other languages?

### ISSUE THREAD

**Issue by 3CE8D2BAC65BDD6AA9** [Azure-Samples/Cognitive-Speech-TTS#195]
Can't wait to use the pronunciation assessment for other languages.  What is the timeline for other languages?

**Comment by yulin-li** [comment]
@yinhew

**Comment by yinhew** [comment]
@3CE8D2BAC65BDD6AA9 can you please briefly describe your scenario? Are you going to ship product with our API? If yes, how will be the estimated traffic? Or is it just prototype / experiment?

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
At this moment, it is for prototype.  Eventually, we want to create an app that has a pronunciation assessment to help students to learn Mandarin.  The app will call the API.  We estimate that the most we have will be 500 samples per day by end of Q1 2021.  Ideally, the assessment is able to assess the pronunciation of a whole sentence, not just one word.

**Comment by mbuotidem** [comment]
Hi, also interested in this. I'm a graduate teaching assistant in French and would like to explore using this as part of a thesis research project next semester.

**Comment by szhaomsft** [comment]
it is supported now
