### ISSUE TITLE
pt-BR-FranciscaNeural using styles

### ISSUE THREAD

**Issue by keikomori** [Azure-Samples/Cognitive-Speech-TTS#199]
Is there any documentation to inform the styles that can be used with Francisca Neural?

For example:

```python
xml_body = ElementTree.Element('speak', version='1.0')
xml_body.set('{http://www.w3.org/XML/1998/namespace}lang', 'pt-BR')
xml_body.set('xmlns:mstts', 'https://www.w3.org/2001/mstts')

voice = ElementTree.SubElement(xml_body, 'voice')
voice.set('name', 'Microsoft Server Speech Text to Speech Voice (pt-BR, FranciscaNeural)')

mstts = ElementTree.SubElement(voice, 'mstts:express-as')
mstts.set('style', 'cheerful')

prosody = ElementTree.SubElement(mstts, 'prosody')
prosody.set('rate', '0%')

body = ElementTree.tostring(xml_body)

```

I tried to use `cheerful` , but I didn't see any change in the voice.

**Comment by boltomli** [comment]
According to <https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#adjust-speaking-styles> it is not reflected what style we can use for the voice yet. Let me check if there's any update recently.
