### ISSUE TITLE
Would you have something similar to the Google "Emphasize"?

### ISSUE THREAD

**Issue by Benoit1980** [Azure-Samples/Cognitive-Speech-TTS#200]
Hello,

I am currently using your API and would like to know what is the closest SSML to the Google emphasize please:

`<emphasis level="moderate">This is an important announcement</emphasis>`
They have 4 levels:
strong
moderate
none
reduced

I would like to have the same "effect" with the Microsoft SSML code, any idea please? 

Thanks,

**Comment by minghuaiping** [comment]
Hi, we plan to flight this feature now. If it is convenient to tell me you region, US for example, I can flight this feature to your region so that you can have a try.

**Comment by Benoit1980** [comment]
Please give me till end of next week and I will let you know as I am too busy working on another project at the moment and will not be able to test it right away :-(. The location I have set in my Azure account is "West Europe". Thanks again!

**Comment by Benoit1980** [comment]
Could you please send me a bit of information on this new feature please? Will we be able to select a journalistic, sad, happy, emphasis? As this really is the main problem, the speech style is super important for users. Thanks

**Comment by minghuaiping** [comment]
Thanks for the feedback. This feature will be available tomorrow in West
Europe region. You can use emphasis together with styles.
The following is some details about how you can use this feature.

The word-level emphasis tuning is only available for these neural voices:
en-US-GuyNeural, en-US-DavisNeural, and en-US-JaneNeural.

Syntax
XMLCopy

<emphasis level="value"></emphasis>

Attribute
AttributeDescriptionRequired or optional
level Indicates the strength of emphasis to be applied:

   - reduced
   - none
   - moderate
   - strong


When the level attribute is not specified, the default level is moderate.
For details on each attribute, see emphasis element
<https://www.w3.org/TR/speech-synthesis11/#S3.2.2> Optional

Example

This SSML snippet demonstrates how the emphasis element is used to add
moderate level emphasis for the word "meetings".
XMLCopy

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="en-US-GuyNeural">
    I can help you join your <emphasis
level="moderate">meetings</emphasis> fast.
    </voice> </speak>

**Comment by Benoit1980** [comment]
Wow, superb! Thank you so much. I am hoping to be able to test this new feature over the week end.

**Comment by minghuaiping** [comment]
This feature is available now. Please refer to this doc about how to
use it.
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#adjust-emphasis:~:text=%3C/speak%3E-,Adjust%20emphasis,-The%20optional%20emphasis

**Comment by minghuaiping** [comment]
How do you feel about this feature? Welcome any feedbacks. @Benoit1980

**Comment by Benoit1980** [comment]
Hi @minghuaiping I have not yet had the time to look at it as I have been busy with side projects. But I am hoping to try this within the next 2 weeks to complete one of my project. Thank you so much for your efforts.
