### ISSUE TITLE
"'cdata' is an unexpected token" when sending text within CDATA

### ISSUE THREAD

**Issue by tzhongyan** [Azure-Samples/Cognitive-Speech-TTS#207]
Recently I was making HTTP request to the `/cognitiveservices/v1` endpoint with a body that looks like this:

```xml
<speak version="1.0" xml:lang="en-US">
    <voice xml:lang="en-US" xml:gender="Female" name="en-US-AriaNeural">
        <![CDATA[She sells seashells by the seashore. The shells she sells are surely seashells. So if she sells shells on the seashore, I'm sure she sells seashore shells.]]>
    </voice>
</speak>
```

and got an error from the HTTP status line that looks like this:
```
HTTP/1.1 500 Synthesis failed. StatusCode: Unknown, Details: 'cdata' is an unexpected token. The expected token is 'CDATA['. Line 1, position 192..
```

I am pretty sure was using CDATA correctly, and had previously used the endpoint like this successfully. Now it seems like Azure side is now lower-casing everything within `<voice>` tag? Or am I mistaken?

**Comment by boltomli** [comment]
Thanks for the issue. I tried and hit the same result. I wonder if anything changed. I'll notify the service provider.

**Comment by szhaomsft** [comment]
supported
