### ISSUE TITLE
MRCP plugin issues

### ISSUE THREAD

**Issue by Patrick-Xiaoice** [Azure-Samples/Cognitive-Speech-TTS#209]
While I was trying to have the plugin installed on my Ubuntu 18.04, I encountered errors while recompiling. When I make, I got 
```
  CXX      src/ms_recog_engine.lo
src/ms_recog_engine.cpp:32:10: fatal error: speechapi_cxx.h: No such file or directory
   32 | #include <speechapi_cxx.h>
```
I have already added the SDK path to SPEECHSDK_ROOT as instructed in the readme, but the error persists. To complete the compilation, I have hardcoded the absolute path to the SDK. 
However, when I start the mrcpserver, it fails to load the plugin. The issue shown in the console is:
```
[INFO]   Load Plugin [MS-Synth-1] [/usr/local/unimrcp/plugin/mssynth.so]
[WARN]   No Version Info Found: mrcp_plugin_version
[INFO]   Load Plugin [MS-Recog-1] [/usr/local/unimrcp/plugin/msrecog.so]
[WARN]   No Version Info Found: mrcp_plugin_version
```

**Comment by yulin-li** [comment]
Hi @Patrick-Xiaoice , firstly, could you try our dockerfile to see if it can compile and run successfully?

And, for the plugin loading issue, I think the SDK so path is not added to `LD_LIBRARY_PATH`. You can use `ldd /usr/local/unimrcp/plugin/mssynth.so` to confirm the dependencies.
