### ISSUE TITLE
Pronunciation Error: Spanish MX Neural Voice - Jorge

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/Cognitive-Speech-TTS#210]
I would like to report that the way the word VIDEO is pronounced for the neural voice named Jorge is not totally accurate.

Your system stresses the word VIDEO sounding like ----> VEE - de - oh     (on the first syllable) 

instead of ----> vi - DEH - oh    (on the second syllable)

If you require an audio sample, I would be more than happy to share it with you.

**Comment by szhaomsft** [comment]
thanks for reporting.

we will take a look

**Comment by ForrestGumb** [comment]
This issue is fixed. Please have a try.

**Comment by inglesuniversal** [comment]
Awesome... I just checked and YES in deed... It works beautifully! Thanks for following up on my request. Good luck!

CORRECTED DEMO AUDIO SAMPLE:

[synth_fixed_es-mx_Jorge.mp3](https://cdn.inglesuniversal.com/audios/mp3/Azure/synth_fixed_es-mx_Jorge.mp3)

**Comment by Jun711** [comment]
@inglesuniversal @szhaomsft @ForrestGumb 
Could you share an example on how to use Spanish neural voices to read accented words? Thank you
The audio I get doesn't pronounce accented characters.  

This is the issue that I opened.
https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/225
