### ISSUE TITLE
could not support chinese(zh-CN), it show : "UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-22"

### ISSUE THREAD

**Issue by haohuancheng** [Azure-Samples/Cognitive-Speech-TTS#211]
( https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/PronunciationAssessment/BrowserJS )
PronunciationAssessment error in sample BrowserJS, when i use chinese charactor, such as: "我买了一双皮鞋。", when i click “Learn Pronunciation” button, the app show error:
**UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-22: ordinal not in range(256).**

**Comment by szhaomsft** [comment]
@yinhew

**Comment by yinhew** [comment]
@haohuancheng the issue was fixed. You can try again with the latest code.
