### ISSUE TITLE
How to use IPA to support Tones in Chinese?

### ISSUE THREAD

**Issue by cshijiel** [Azure-Samples/Cognitive-Speech-TTS#213]
```xml
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="zh-CN">
    <voice name="zh-CN-XiaoxiaoNeural" style="newscast">
        <phoneme alphabet="sapi" ph="fen 2 ci 4">分词</phoneme>。
        <phoneme alphabet="sapi" ph="niu 4 bi 2">牛逼</phoneme>。
        <phoneme alphabet="ipa" ph="ɚ˥">耳</phoneme>。。。
    </voice>
</speak>
```
I tried to use this description, but failed.

**Comment by szhaomsft** [comment]
SAPI phone can work with tones.

**Comment by jiajzhan** [comment]
@cshijiel IPA support Chinese tones.
Here I list the IPA tone levels (IPA unicode/decimal and symbol) supported by Microsoft TTS.
- tone level 1:  783	̏
- tone level 2: 768	̀
- tone level 3: 772	̄
- tone level 4: 769	́
- tone level 5: 779	̋

According to https://en.wikipedia.org/wiki/Tone_letter, it shows how to use tone with IPA for Chinese. 
E.g. <phoneme alphabet='ipa' ph='nà̏́'>test</phoneme> to describe the 3rd tone which is the same as pinyin 'na 3'.

But I still suggest you to use SAPI phones  as its much easier to use.
