### ISSUE TITLE
How to get phonemes for other languages?

### ISSUE THREAD

**Issue by XavierMarchena** [Azure-Samples/Cognitive-Speech-TTS#220]
I tried using French and Brazilian Portuguese, and it works in both languages, but it doesn't return the value for each phoneme
```
language = "pt-BR"
voice = "Microsoft Server Speech Text to Speech Voice (pt-BR, FranciscaNeural)"
```

`{
  "Duration": 19400000, 
  "NBest": [
    {
      "AccuracyScore": 100.0, 
      "CompletenessScore": 100.0, 
      "Display": "Como o senhor se chama?", 
      "FluencyScore": 100.0, 
      "ITN": "Como o senhor se chama", 
      "Lexical": "Como o senhor se chama", 
      "MaskedITN": "como o senhor se chama", 
      "PronScore": 100.0, 
      "Words": [
        {
          "AccuracyScore": 100.0, 
          "Duration": 3300000, 
          "ErrorType": "None", 
          "Offset": 3000000, 
          "Phonemes": [
            {
              "AccuracyScore": 100.0, 
              "Duration": 900000, 
              "Offset": 3000000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 700000, 
              "Offset": 4000000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 900000, 
              "Offset": 4800000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 500000, 
              "Offset": 5800000, 
              "Phoneme": ""
            }
          ], 
          "Word": "Como"
        }, 
        {
          "AccuracyScore": 100.0, 
          "Duration": 500000, 
          "ErrorType": "None", 
          "Offset": 6400000, 
          "Phonemes": [
            {
              "AccuracyScore": 100.0, 
              "Duration": 500000, 
              "Offset": 6400000, 
              "Phoneme": ""
            }
          ], 
          "Word": "o"
        }, 
        {
          "AccuracyScore": 100.0, 
          "Duration": 4700000, 
          "ErrorType": "None", 
          "Offset": 7000000, 
          "Phonemes": [
            {
              "AccuracyScore": 100.0, 
              "Duration": 700000, 
              "Offset": 7000000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 500000, 
              "Offset": 7800000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 1700000, 
              "Offset": 8400000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 900000, 
              "Offset": 10200000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 500000, 
              "Offset": 11200000, 
              "Phoneme": ""
            }
          ], 
          "Word": "senhor"
        }, 
        {
          "AccuracyScore": 100.0, 
          "Duration": 2100000, 
          "ErrorType": "None", 
          "Offset": 11800000, 
          "Phonemes": [
            {
              "AccuracyScore": 100.0, 
              "Duration": 900000, 
              "Offset": 11800000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 1100000, 
              "Offset": 12800000, 
              "Phoneme": ""
            }
          ], 
          "Word": "se"
        }, 
        {
          "AccuracyScore": 100.0, 
          "Duration": 5800000, 
          "ErrorType": "None", 
          "Offset": 14000000, 
          "Phonemes": [
            {
              "AccuracyScore": 100.0, 
              "Duration": 1100000, 
              "Offset": 14000000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 1000000, 
              "Offset": 15200000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 1000000, 
              "Offset": 16300000, 
              "Phoneme": ""
            }, 
            {
              "AccuracyScore": 100.0, 
              "Duration": 2400000, 
              "Offset": 17400000, 
              "Phoneme": ""
            }
          ], 
          "Word": "chama"
        }
      ]
    }
  ], 
  "Offset": 2800000, 
  "RecognitionStatus": "Success"
}
`

**Comment by yulin-li** [comment]
Looks it's a Pronunciation Assessment issue, adding @yinhew

**Comment by yinhew** [comment]
@XavierMarchena we currently don't expose phoneme name by default for non-English languages.
We have a gated way to expose them to whitelisted customer with enough business deal.
If your project is going to product with enough traffic (e.g. >1k hours per month), we can have some further discussion about the whitelist.
You can start this by emailing yinhew@microsoft.com and lisma@microsoft.com.
