### ISSUE TITLE
Translation failed :Exception with an error code: 0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND) - Azure Linux App Service

### ISSUE THREAD

**Issue by willieburger34** [Azure-Samples/Cognitive-Speech-TTS#223]
Hi,

I am getting this exception when using text to speech on an Azure App Service (.net 6) Linux

Translation failed :Exception with an error code: 0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND)

The code execute perfectly on my local machine and only errors on the server itself.

The code below is used to execute using the westus region. TextToRead contains "Hello world"

  using (var synthesizer = new SpeechSynthesizer(config))
            {
                
                using (var result = await synthesizer.SpeakTextAsync(textToRead))
                {
                    if (result.Reason == ResultReason.SynthesizingAudioCompleted)
                    {
                        return result.AudioData;
                    }
                    else if (result.Reason == ResultReason.Canceled)
                    {
                        var cancellation = SpeechSynthesisCancellationDetails.FromResult(result);

                        StringBuilder sb = new StringBuilder();
                        sb.AppendLine($"CANCELED: Reason={cancellation.Reason}");
                        sb.AppendLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                        sb.AppendLine($"CANCELED: ErrorDetails=[{cancellation.ErrorDetails}]");

                        throw new TextToSpeechException(sb.ToString());
                    }
                    throw new TextToSpeechException("Unknown error occured: " + result.Reason.ToString());
                }
            }

Is there anything specific we need to do to host on a Linux App Service in Azure?

Thank you.

**Comment by szhaomsft** [comment]
SpeakTextAsync is speaking to a sound card.  

can you set up the output to a file or stream?
