### ISSUE TITLE
Speaking styles are ignored

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/Cognitive-Speech-TTS#227]
Hi

I pasted the speaking style SSML example from [the SSML documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp) inside the [TTS demo](https://azure.microsoft.com/nl-nl/services/cognitive-services/text-to-speech/#features) but changing the style doesn't seem to change the audio. Is this element ignored? 

The example:
```
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="en-US-AriaNeural">
        <mstts:express-as style="cheerful">
            That'd be just amazing!
        </mstts:express-as>
    </voice>
</speak>
```

Regards

**Comment by szhaomsft** [comment]
we can take a look

**Comment by LuckerYi** [comment]
> 

It seems **OK** when I paste the SSML code you shared, pls kindly retry if there are any browsers or cache errors : )

**Comment by LuckerYi** [comment]
> Hi
> 
> I pasted the speaking style SSML example from [the SSML documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp) inside the [TTS demo](https://azure.microsoft.com/nl-nl/services/cognitive-services/text-to-speech/#features) but changing the style doesn't seem to change the audio. Is this element ignored?
> 
> The example:
> 
> ```
> <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
>        xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="en-US">
>     <voice name="en-US-AriaNeural">
>         <mstts:express-as style="cheerful">
>             That'd be just amazing!
>         </mstts:express-as>
>     </voice>
> </speak>
> ```
> 
> Regards

It seems OK when I paste the SSML code you shared, pls kindly retry if there are any browsers or cache errors : )

**Comment by Jxlle** [comment]
Hi @LuckerYi 

Sorry for the late reply, I seem to have missed your reply.
Indeed, I didn't initially hear the difference but I do now. I did however notice that some voices do not have these styles yet by experimenting with them (e.g. en-US Eric Neural). Is there a list available somewhere that shows which voices support this feature and which do not?
