### ISSUE TITLE
SSML audio examples don't work

### ISSUE THREAD

**Issue by johnmalatras** [Azure-Samples/Cognitive-Speech-TTS#229]
Hi, we're looking at implementing Azure text to speech at a large scale but are having several difficulties getting setup. We'd like to both include audio snippets and background audio in our SSML, but neither seem to work. It doesn't appear to be user error because neither of the examples found here work either: https://github.com/Azure-Samples/Cognitive-Speech-TTS/wiki/How-to-use-SSML

The ["Use SSML Audio"](https://github.com/Azure-Samples/Cognitive-Speech-TTS/wiki/How-to-use-SSML#use-ssml-audio) example fails with a 500 and no error information.

The ["Use background audio with Neural voice"](https://github.com/Azure-Samples/Cognitive-Speech-TTS/wiki/How-to-use-SSML#use-background-audio-with-neural-voice) example returns an empty audio file

**Comment by johnmalatras** [comment]
FYI @szhaomsft

**Comment by yulin-li** [comment]
duplicated of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1492 close here
