### ISSUE TITLE
speechapi_cxx.h: No such file or directory

### ISSUE THREAD

**Issue by herbiel** [Azure-Samples/Cognitive-Speech-TTS#231]
this build problem 
src/ms_recog_engine.cpp:32:10: fatal error: speechapi_cxx.h: No such file or directory

[root@centos unimrcp-1.6.0]# env | grep sdk
LD_LIBRARY_PATH=/usr/local/speechsdk/lib/x64:/usr/local/speechsdk/lib/x64
[root@centos unimrcp-1.6.0]# ls -l /usr/local/speechsdk/lib/x64
总用量 4088
-rw-rw-rw-. 1 root root 2912448 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.core.so
-rw-rw-rw-. 1 root root  100360 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so
-rw-rw-rw-. 1 root root   71680 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.extension.codec.so
-rw-rw-rw-. 1 root root  411680 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.extension.kws.so
-rw-rw-rw-. 1 root root  265240 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.extension.lu.so
-rw-rw-rw-. 1 root root  411808 6月   1 17:53 libMicrosoft.CognitiveServices.Speech.extension.mas.so

i check i have install sdk

**Comment by herbiel** [comment]
i have run export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SPEECHSDK_ROOT/lib/x64" before build

**Comment by yulin-li** [comment]
Follow this if you are trying the MRCP sample
