### ISSUE TITLE
speech_sdk_region is not working on mrcp ?

### ISSUE THREAD

**Issue by herbiel** [Azure-Samples/Cognitive-Speech-TTS#237]
[Cognitive-Speech-TTS](https://github.com/Azure-Samples/Cognitive-Speech-TTS)/[MRCP](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/MRCP)/[sample-conf](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/MRCP/sample-conf)/config.json

In this config.json ,i have set    "speech_sdk_region": "southeastasia",but i capture the data,i find the packet will be sent to 20.43.132.1 ,it's American address,so it's not  on southeastasia?

**Comment by yulin-li** [comment]
Could you try to [enable SDK logging](https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging) to see the real traffic endpoint?
