### ISSUE TITLE
Text to Speech New Users No Longer Supported

### ISSUE THREAD

**Issue by Wholebitmedia** [Azure-Samples/Cognitive-Speech-TTS#244]
I  received a console error in Unity that states that new users of the TTS services are no longer supported.  I have been working with this since 2018 but have recently reinstated my Azure via the Startup Founders Hub.  Here is the error log.

CANCELED: ErrorDetails=[Connection was closed by the remote host. Error code: 1007. Error details: Starting September 1st, 2021 standard voices will no longer be supported for new users. Please use n USP state: 3. Received audio size: 0 bytes.]

**Comment by szhaomsft** [comment]
Use neural voice
