### ISSUE TITLE
TTS word boundary inconsistencies 

### ISSUE THREAD

**Issue by GoncaloBastos** [Azure-Samples/Cognitive-Speech-TTS#245]
Depending on whether you apply pronunciation changes through the lexicon or using the <sub alias> tag, the returned word boundary will differ. 

When using the lexicon, the original text is returned in word boundary, while using the tag, the value inside the alias attribute is what is returned in word boundary.

Based on the example usage for WordBoundary (closed captions/subtitles), I believe the expected behaviour should be to return the original text (i.e. lexicon behaviour).

**Comment by Kerry-LinZhang** [comment]
Hi @GoncaloBastos thanks for the feedback, and we have already fixed the issue you reported, could you please verify if it still exists? If not, do you mind providing us a specific example for further investigation? Thanks a lot.
