### ISSUE TITLE
Now /ackaud  has no response.

### ISSUE THREAD

**Issue by haohuancheng** [Azure-Samples/Cognitive-Speech-TTS#248]
From now on, the code was no use. when run to this endpoint, there are no response when call: "requests.post" code. may be the url is invalid now:
**url = "https://%s.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=%s" % (region, language)**

**Comment by haohuancheng** [comment]
The demo app bug from here:
https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/PronunciationAssessment/BrowserJS

**Comment by yinhew** [comment]
Hi, @haohuancheng 

Did this code ever work for you before?

Thanks,
Yinhe

**Comment by haohuancheng** [comment]
![image](https://user-images.githubusercontent.com/17491618/201273109-f8a73d8b-f97a-465d-aac9-74ec97912f9a.png)

The above is the display interface diagram of the runtime code.

**Comment by yinhew** [comment]
Hi, @haohuancheng 

Can you try to append &usePipelineVersion=0 to the url and see if it works?

Thanks,
Yinhe

**Comment by haohuancheng** [comment]
Excellent! The problem is solved.
The official support is strong!

**Comment by haohuancheng** [comment]
Thank you very much!  @yinhew

**Comment by forleemaster** [comment]
How should I modify the IPA phonetic symbols used in the JSON data I want to return?
