### ISSUE TITLE
A similar issue to not getting any response from /ackaud 

### ISSUE THREAD

**Issue by CharredOak** [Azure-Samples/Cognitive-Speech-TTS#260]
I've tried resetting my virtual environment and cannot get the post request to go through.

In the browser, the "Stop" button does not seem to be triggering any functions that use the audio steam.

index.js does not seem to have anything wrong unless I'm missing something.
If the latest version of microsoft.cognitiveservices.speech.sdk.bundle.js (1.24.1) changed something I don't think it would get stuck with the audio steam.

![image](https://user-images.githubusercontent.com/123342335/213956656-29bf2db7-41a3-4eaa-a988-b6704afcc9b4.png)

Am I missing something obvious?
(I am new on github and I am trying to learn Azure)

**Comment by Kerry-LinZhang** [comment]
Hi @CharredOak well received for the feedback, we are checking the problem, and will keep you updated for the investigation

**Comment by hongmeizhou** [comment]
hi @CharredOak 
It works well in my local pc. I think you forgot to set value for "subscription_key" and "region" in you application.py file.  If it not works please let me know,  I'll check the problem again.
