### ISSUE TITLE
JS file invalidation

### ISSUE THREAD

**Issue by yingshang** [Azure-Samples/Cognitive-Speech-TTS#271]
https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/PronunciationAssessment/BrowserJS/templates/readalong.html#L8

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/PronunciationAssessment/BrowserJS/templates/index.html#L9

![image](https://user-images.githubusercontent.com/11006249/226960032-13c00010-9aed-4632-a781-97e54814b836.png)

**Comment by Kerry-LinZhang** [comment]
Hi @yingshang thanks for your feedback, we are looking into it and will get back to you as soon as these is any progress on it

**Comment by Kerry-LinZhang** [comment]
Hi @yingshang 

It looks like you were using a kit code from the w3schools.com web site. That kit code is intended to be used on w3schools.com and they a referrer check now on their kit. You can get your own free kit code here **https://fontawesome.com/start**. After getting our free kit code you can just replace the one from w3schools.com and everything should load just fine.

**Comment by yingshang** [comment]
Thanks!
