### ISSUE TITLE
tts for Android

### ISSUE THREAD

**Issue by 76alex67** [Azure-Samples/Cognitive-Speech-TTS#274]
I am very lucky to find your open source project on GitHub: TTS Serve for Android, but I just used for a few days. I want to change to my own Azure API, but I don’t know how to operate. Professional origin, I feel very unfortunate when you see the project you have to turn off. I hope you have time to guide me how to operate. Thank you very much. I wish the boss a fortune!

**Comment by Kerry-LinZhang** [comment]
Hi @76alex67 could you please give detailed description about what problem you have, the scenario, the blocking issue?
