### ISSUE TITLE
Unclear / Inconsistent behavior of nesting prosody

### ISSUE THREAD

**Issue by lukas-parloa** [Azure-Samples/Cognitive-Speech-TTS#295]
## Request

Need clarification and / or documentation on expected TTS behavior with `prosody` tag, applying different settings to different parts of a prompt.

Nesting prosody with different combinations seems to apply the properties to a complete prompt (rate & pitch), while in other cases it seems to work as expected (rate & contour).

If you could clarify and explain what the expected behavior and recommended usage is, it would help produce correct SSML from our application in various scenarios.

## Context

The goal is to have a faster/slower voice, and still allow prosody adjustments on individual words or sentences.

According to the documentation, `prosody` is a valid tag inside of `prosody`: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice#adjust-prosody

All tests are performed in the Speech Studio, the actual use case is an application via the JavaScript SDK.

_Flattening and merging prosody tags is something we would ideally like to avoid to save the effort_

## Case 1: Rate & Pitch 

_extreme values are used for demonstration purposes_

**Prompt description**

* Say "Hello. How are you doing?" in English
* Applying -20% rate
* "How are you doing?" should have a pitch "+30%"

### Test case

Using the following SSML, we can test

1. Nesting the pitch change inside of the rate tag (manually created)
2. Using the Speech Studio UI, a flat prosody structure is produced 

```
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US"><voice name="en-US-JennyNeural"><bookmark mark="nested" />
<prosody rate="-20.00%">Hello. <prosody pitch="+30%">How are you doing?</prosody></prosody>
<bookmark mark="flat" />
<prosody rate="-20.00%">Hello. </prosody><prosody rate="-20.00%" pitch="+30.00%">How are you doing?</prosody>
</voice></speak>
```

### Result

* The nested SSML applies the pitch change to the full paragraph.
* The flat SSML applies the rate correctly only to the wrapped sentence

### Expectation

Both produce the same result.

## Case 2: Rate & Contour

**Prompt description**

* Applying -20% rate
* Custom contour on "Verstanden."

### Test case

Using the following SSML, we can test

1. Original pronunciation without contour (baseline)
2. Nesting the cntour change inside of the rate tag (manually created)
3. Using the Speech Studio UI, a flat prosody structure is produced 

```
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="de-DE"><voice name="de-DE-KatjaNeural">
<bookmark mark="no contour" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. Verstanden.</prosody>
<bookmark mark="nested" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. <prosody contour="(8%, +85%) (47%, -10%) (100%, -18%)">Verstanden.</prosody></prosody>
<bookmark mark="flat" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. </prosody><prosody pitch="-20.00%" contour="(8%, +85%) (47%, -10%) (100%, -18%)">Verstanden.</prosody></voice></speak>
```

### Result

Both contour variations seem to produce the same results

<img width="914" alt="image" src="https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/123259762/b8852c15-578c-4e4e-8b5f-72c9ed8d4979">

**Comment by Kerry-LinZhang** [comment]
Hi @lukas-parloa thanks for your feedback, I see same one here reported, https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2039

Currently the owner is taking a leave this week, I will follow up with him as soon as he is back, thanks for your understanding.

**Comment by Kerry-LinZhang** [comment]
Debug ongoing, these two tags should have the same behavior.

**Comment by Kerry-LinZhang** [comment]
Let me continue pushing for the status update

**Comment by Kerry-LinZhang** [comment]
Hi @lukas-parloa 

For Case 1, currently the result we checked are aligned, the pitch applies only to the wrapped sentence, would you please try again?

And for Case 2, We have a suggestion when using contour tag for single words: to generate noticeable single-word adjustment effects, it might be appropriate to increase the range of adjustments, such as including the preceding sentence in the adjustment scope.

**Comment by Kerry-LinZhang** [comment]
Hi @lukas-parloa We have double checked the first case, and still cannot reproduce the issue on WestEurope, they are the same output as the one in your first link shared: https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/123259762/4d556915-516c-44c0-9214-c068b859fccd

I have also attached the samples from our side for your reference. Would you mind trying other regions or testing other sentences, if there is still any problem, please feel free to let us know.
[Jenny.zip](https://github.com/Azure-Samples/Cognitive-Speech-TTS/files/15260358/Jenny.zip)
