### ISSUE TITLE
List of phonemes per speaker for Azure TTS?

### ISSUE THREAD

**Issue by lancejpollard** [Azure-Samples/Cognitive-Speech-TTS#297]
Hello is there a list of phonemes per speaker guide for azure, similar to what google offers here https://cloud.google.com/text-to-speech/docs/phonemes ?

I see the list of languages [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts), with (2) footnote saying those with # 2 don't have phoneme support. But of those that _do_ have phoneme support, what are the supported phonemes? How do I tell if the speaker will support my required phonemes?

Also, do you have a test/playground to type in (in SSML even) to have a speaker speak your custom text online, like [AWS Polly does](https://us-east-1.console.aws.amazon.com/polly/home/SynthesizeSpeech)? That would help, that way I could test for phonemes there too.

<img width="1381" alt="Screenshot 2023-08-16 at 8 02 45 PM" src="https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/28718/9b3345d1-3146-4e8b-b51a-93b78c8f635c">

**Comment by Kerry-LinZhang** [comment]
Hi @lancejpollard thanks for your feedback, @jiajzhan could you please help to take a look?

**Comment by szhaomsft** [comment]
you can sheck speech studio: audio content creation tool which allows you input phonemes
