### ISSUE TITLE
SSML grammar clarifications

### ISSUE THREAD

**Issue by frnds1** [Azure-Samples/Cognitive-Speech-TTS#304]
In the ssml_mstts.xsd:

silence element type attribute has redundant enumeration values based on capitalization. Is there are default or preferred format? Is one likely to be deprecated?

<xs:enumeration value="Leading" />
<xs:enumeration value="leading" />

express-as element style attribute has missing documented styles. Are these deprecated?

style="advertisement_upbeat"	Expresses an excited and high-energy tone for promoting a product or service.
style="documentary-narration"	Narrates documentaries in a relaxed, interested, and informative style suitable for dubbing documentaries, expert commentary, and similar content.
style="envious"	Expresses a tone of admiration when you desire something that someone else has.
style="excited"	Expresses an upbeat and hopeful tone. It sounds like something great is happening and the speaker is happy about it.
style="friendly"	Expresses a pleasant, inviting, and warm tone. It sounds sincere and caring.
style="hopeful"	Expresses a warm and yearning tone. It sounds like something good will happen to the speaker.
style="narration-relaxed"	Expresses a soothing and melodious tone for content reading.
style="poetry-reading"	Expresses an emotional and rhythmic tone while reading a poem.
style="shouting"	Expresses a tone that sounds as if the voice is distant or in another location and making an effort to be clearly heard.
style="sports_commentary"	Expresses a relaxed and interested tone for broadcasting a sports event.
style="sports_commentary_excited"	Expresses an intensive and energetic tone for broadcasting exciting moments in a sports event.
style="whispering"	Expresses a soft tone that's trying to make a quiet and gentle sound.
style="terrified"	Expresses a scared tone, with a faster pace and a shakier voice. It sounds like the speaker is in an unsteady and frantic status.
style="unfriendly"	Expresses a cold and indifferent tone.

**Comment by niuzheng168** [comment]
For the casing issue, we support both lower case can capitalization, there is no prefer format.

For express-as, the xsd is out of date, we will update later. Please honor the ones in azure doc.
