### ISSUE TITLE
SpeechSDK in C# for speech to text avatar

### ISSUE THREAD

**Issue by shilpaCM** [Azure-Samples/Cognitive-Speech-TTS#315]
Hi,
we see that speechSDK for speech to text avatar is available on in JS framework. What is the equivalent C# SDK to use.  
SpeechSDK.AvatarConfig,  SpeechSDK.AvatarVideoFormat, and SpeechSDK.AvatarSynthesizer methods.
References around will be useful.

**Comment by Kerry-LinZhang** [comment]
Hi @shilpaCM  for the SDK related feedback, you can report it on this page to get a quicker support: 

[Azure-Samples/cognitive-services-speech-sdk: Sample code for the Microsoft Cognitive Services Speech SDK (github.com)](https://github.com/Azure-Samples/cognitive-services-speech-sdk)
