### ISSUE TITLE
Pronunciation Assessment results are bad when requests sent concurrently

### ISSUE THREAD

**Issue by jaskiran-profjim** [Azure-Samples/Cognitive-Speech-TTS#316]
The results of a perfectly sounding audio produces a very erroneous result from the Pronunciation Assessment SDK, when about 10-15 requests are sent in parallel from the same machine, whereas when the same requests are processed serially, the results are good. 

I have noticed that when I was sending concurrent requests from 5-6 different servers/IPs, this issue didn't occur. When I updated my code to send requests through threading from the same server/IP, there was a very significant difference in the error rate. And this is when the audios in question are impeccable, they have no pronunciation issue, yet the word level metrics show almost each word as omitted. 

Is it an issue with the concurrency limit? Or how concurrent requests from the same IP are handled? Has anyone faced anything similar?

**Comment by wangkenpu** [comment]
Can you share the sample code to us to reproduce the issue?

**Comment by iamwwn** [comment]
I compare with hundreds of wav recordings in serial running and parallel running, the Pronunciation Assessments results are same.

**Comment by iamwwn** [comment]
I cannot repro the issue, I tested a few utterances between serial running and parallel running (16 threads),  the results shows same between serial and parallel. 
![image](https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/88471044/7ea5bea0-aefb-4f86-aa00-7ced4fb24871)
