### ISSUE TITLE
Possible typo in dataset

### ISSUE THREAD

**Issue by NewMountain** [Azure-Samples/Cognitive-Speech-TTS#318]
Hi all!

I was working through this dataset for a custom voice and noticed an error in line 53 of the general English text.

I believe `The flour in white breads, bagels, pastries and pasta has lost the grain's fibber-rich outer layer during the refining process."`

should instead be `fiber-rich`

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/f006f1233e75dbe7dc4682695282e8fbfd85f85d/CustomVoice/script/English%20(United%20States)_en-US/0000000001_0300000050_General.txt#L53

I can submit a PR with the correction if useful.

**Comment by Kerry-LinZhang** [comment]
Thanks for the feedback, we will check and refine for it

**Comment by ForrestGumb** [comment]
Thank you for the feedback. Fixed.
