### ISSUE TITLE
How to add the EnableProsodyAssessment in the api request? using JS

### ISSUE THREAD

**Issue by disio1126** [Azure-Samples/Cognitive-Speech-TTS#319]
Hello, first of all thank you for your time.
I am creating a JS widget to analyse pronunciation.
using the services of Speech Studio and its Pronunciation Assessment Tool. All good so far, just a small detail, exploring its functions in the Speech Studio I noticed that there shows in the JSON response some values that my widget does not throw which is the **Prosody Score** and consequently to see the results of the syllables this does not throw other important information such as Feedback where reports such as Unexpected Break or Miss Break are found.

![1](https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/152834791/17b1d1c3-51ee-4fa6-9389-abad2f61fd00)
![2](https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/152834791/383a0785-dda4-4746-80ee-a12e8b8025c7)
![3](https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/152834791/44d1028e-0950-49e8-94f9-2f4c7fdc2aa2)

Looking for information in the posts of microsofot I came to the conclusion that it is because of the following condition in the request: **EnableProsodyAssessment** that should be sent in True since by default this deactivated, I have tried to send it of all the possible forms in the each of parameters but it continues without giving me results, some idea of how to soulucionarlo? 

**This is my code**

var subscriptionKey = "XXXXXXXXXXXXXXXXXXX";
    var region = "eastus";
    
    const referenceText = reftext.value;
    const enableProsodyAssessment = true;
var pronAssessmentParamsJson = '{"ReferenceText":"' + referenceText + '","GradingSystem":"HundredMark","Granularity":"Phoneme","**enableProsodyAssessment":"True",**"EnableMiscue":"True","PhonemeAlphabet":"IPA","NBestPhonemeCount":"5","Dimension":"Comprehensive"}';

var pronAssessmentParams = btoa(unescape(encodeURIComponent(pronAssessmentParamsJson)));

        const apiUrl = `https://${region}.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=${idioma_general}`;

        const options = {
            method: 'POST',
            headers: {
                'Accept': 'application/json;text/xml',
                'Content-Type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
                'Ocp-Apim-Subscription-Key': subscriptionKey,
                'Pronunciation-Assessment': pronAssessmentParams
             
            },
            body: blob
        };

**Comment by wangkenpu** [comment]
REAS API doesn't suppor prosody score currently. You can try to use speech sdk.

FYI. https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/node
