### ISSUE TITLE
Azure Cognitive Speech TTS does not work on Server 2012R2 since 2024-01

### ISSUE THREAD

**Issue by jgriede** [Azure-Samples/Cognitive-Speech-TTS#320]
The same issue as https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/221 re-appeared (after 2 years) as of 2nd januari 2024.

Only these 3 TLS 1.2 ciphers seem to be active now for api.cognitive.microsofttranslator.com.

TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

While api.microsofttranslator.com and api.cognitive.microsoft.com still have much more TLS 1.2 ciphers active...

My company does have a 2012 R2 ESU support contract with Microsoft so some other TLS 1.2 ciphers should still be supported in Azure.

@Microsoft please fix this again asap in Azure.

**Comment by Kerry-LinZhang** [comment]
Hi @jgriede Thanks for your feedback, this may relate to Translator Endpoint, and we only track TTS feedback here, would you please try contact certain team for it, suggest to feedback at: https://www.microsoft.com/en-us/translator/help/
