### ISSUE TITLE
Possible bug synthesizing speech

### ISSUE THREAD

**Issue by AfonsoCunha** [Azure-Samples/Cognitive-Speech-TTS#323]
Hi. 
I may have identified a bug in the speech generation that causes certain text segments to be synthesized twice. This issue occurs with multilingual voices. 

You can reproduce the issue with the following SSML code. The corresponding audio file will have the content in the third `<lang> `tag repeated. 

```
<?xml version="1.0" encoding="UTF-8"?>
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts"
    xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
    <voice name="en-US-RyanMultilingualNeural">
        <prosody rate="0%" pitch="0%">
            <lang xml:lang="pt-PT">No final da idade do bronze e em particular na Dinastia </lang>
            <lang xml:lang="ja-JP">Han</lang>
            <lang xml:lang="pt-PT">, que foi desde 206 a.C. a 220 depois de Cristo, a prática da
                criação de uma réplica do mundo para acompanhar o defunto no além, e do enterro dos
                mortos com figuras substitutas e modelos em vez de seres humanos, animais e bens
                utilitários, impulsionou o desenvolvimento de um importante novo sector da cerâmica,
                o mobiliário.</lang>
        </prosody>
    </voice>
</speak>

```

**Comment by AfonsoCunha** [comment]
Here is the SSML: 
`<?xml version="1.0" encoding="UTF-8"?>
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts"
    xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
    <voice name="en-US-RyanMultilingualNeural">
        <lexicon uri="https://zoomguide-static.s3.eu-west-3.amazonaws.com/lexicon_pt_PT.xml" />
        <prosody rate="0%" pitch="0%">
            <lang xml:lang="pt-PT">No final da idade do bronze e em particular na Dinastia </lang>
            <lang xml:lang="ja-JP">Han</lang>
            <lang xml:lang="pt-PT">, que foi desde 206 a.C. a 220 depois de Cristo, a prática da
                criação de uma réplica do mundo para acompanhar o defunto no além, e do enterro dos
                mortos com figuras substitutas e modelos em vez de seres humanos, animais e bens
                utilitários, impulsionou o desenvolvimento de um importante novo sector da cerâmica,
                o mobiliário.</lang>
        </prosody>
    </voice>
</speak>`

**Comment by Kerry-LinZhang** [comment]
Thanks for the feedback, we are investigating for it.

**Comment by jinxp** [comment]
Hi @AfonsoCunha,

I checked internal, cannot repro the issue,  and the wav sound fine for me. 
Here shared wav and relevant meta info which contains the expand words.  pls help verify too. 
[multi.zip](https://github.com/Azure-Samples/Cognitive-Speech-TTS/files/15061469/multi.zip)

Pls help afford more details：
   1. target region  
   2. demo issue wave for us compare.  
   3. pls help highlight the **specific issue text** which was important to position the issue quickly.  
   4. any other details about the bug, pls feel free list here.

**Comment by Kerry-LinZhang** [comment]
Hi @AfonsoCunha we have double checked the SSML you reported, the third <lang>tag content is read only once as expected, would you please try again?

<?xml version="1.0" encoding="UTF-8"?>
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts"
    xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
    <voice name="en-US-RyanMultilingualNeural">
        <prosody rate="0%" pitch="0%">
            <lang xml:lang="pt-PT">No final da idade do bronze e em particular na Dinastia </lang>
            <lang xml:lang="ja-JP">Han</lang>
            <lang xml:lang="pt-PT">, que foi desde 206 a.C. a 220 depois de Cristo, a prática da
                criação de uma réplica do mundo para acompanhar o defunto no além, e do enterro dos
                mortos com figuras substitutas e modelos em vez de seres humanos, animais e bens
                utilitários, impulsionou o desenvolvimento de um importante novo sector da cerâmica,
                o mobiliário.</lang>
        </prosody>
    </voice>
</speak>
