### ISSUE TITLE
bookmark tag returning junk for specific voice name

### ISSUE THREAD

**Issue by branaway** [Azure-Samples/Cognitive-Speech-TTS#328]
for 
```
<speak version='1.0' xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang='en-US'>
        <voice name='zh-CN-XiaoxiaoMultilingualNeural'>
anything <bookmark mark="hello"/>  anything
        </voice>
      </speak>
      
```
The bookmark event returned weird characters: 배萓罵
      
Other models works fine, such as: zh-CN-XiaoyuMultilingualNeural.

How does the bookmark have anything to do with the voice....

**Comment by Kerry-LinZhang** [comment]
Hi @branaway is this the same feedback as https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/828 you reported?
If so, shall we close this one and follow up with '828'?

**Comment by branaway** [comment]
yes, sorry for the duplication.

**Comment by Kerry-LinZhang** [comment]
Thanks @branaway for the confirmation!
