### ISSUE TITLE
Pronunciation Assessment work not correctly

### ISSUE THREAD

**Issue by BigVeila** [Azure-Samples/Cognitive-Speech-TTS#332]
I am developing an app for Korean learning.
I always get 100 points even though I'm sure I don't speak correctly.
It seems that other languages ​​besides English do not give good results.

**Comment by wangkenpu** [comment]
Thanks for your response. Can you share some samples, including waveform and samples to help us to reproduce your issue? @BigVeila

**Comment by BigVeila** [comment]
Yes, Here is my example sentence
안녕하세요 감사합니다
[sampleVoice.wav.zip](https://github.com/user-attachments/files/16703151/sampleVoice.wav.zip)
You can also test on Azure AI Studio, the results are similar.

![Screenshot 2024-08-22 at 09 17 38](https://github.com/user-attachments/assets/07ef77a9-f956-4714-a776-3402e5d805cb)

**Comment by BigVeila** [comment]
> Thanks for your response. Can you share some samples, including waveform and samples to help us to reproduce your issue? @BigVeila

**Comment by BigVeila** [comment]
@wangkenpu We found the STT/TTS of Korean language to be of poor quality as well, we tried it with several other languages ​​and found it to be very good, except for Korean.

**Comment by wangkenpu** [comment]
@BigVeila After deep investigations, we have fixed the issue of pronunciation assessment. The change will be deployed in 1 week.

For STT and TTS's issues, please open another ticket.

**Comment by wangkenpu** [comment]
No response for a long time. Please close the issue. @szhaomsft
