### ISSUE TITLE
my gosh。only java simple works

### ISSUE THREAD

**Issue by MHuangXin** [Azure-Samples/Cognitive-Speech-TTS#36]
my gosh。only java simple works

**Comment by neoguo0601** [comment]
@MHuangXin Can you provide some more detailes so that we can fix it? Thanks

**Comment by MHuangXin** [comment]
@neoguo0601 
1.in this response tss only  works int project “Cognitive-Speech-TTS/Samples-Http/Java/TTSSample/“ 。
2.“Android/TTSSample“，“Cognitive-Speech-TTS/Android/Sample/” dont work.
3.u can clone these project and test.

**Comment by neoguo0601** [comment]
@MHuangXin Thanks for your detailes. After replace the speechsdk.aar file has been able to use.
please try again. Thanks
