### ISSUE TITLE
C# example does not work

### ISSUE THREAD

**Issue by bryanjhogan** [Azure-Samples/Cognitive-Speech-TTS#46]
I put in my key and got the following 

Starting Authtentication
Token: eyJ0eXAiOi very long token //snip//

Starting TTSSample request code execution.
Response status code: [Forbidden]
Unable to complete the TTS request: [CognitiveServicesTTS.GenericEventArgs`1[System.Exception]]

**Comment by szhaomsft** [comment]
it works for me.    

can you share your ssml?

**Comment by szhaomsft** [comment]
also, free key has throttling.  don't send a lot of request at same time

**Comment by bryanjhogan** [comment]
I don't have an ssml file and I don't see one in the example.


Maybe you can tell me if I put the keys in the right places - 

Redacted deployment info - 
![image](https://cloud.githubusercontent.com/assets/5768871/26107728/394519f0-3a18-11e7-9ee6-62d5340f70d9.png)


And my redacted app.config


```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <appSettings>
    <add key="luisAppID" value="75..." />
    <add key="luisSubscriptionID" value="50..." />
    <add key="ShortWaveFile" value="whatstheweatherlike.wav" />
    <add key="LongWaveFile" value="batman.wav" />
    <!-- 
     Enter an optional authentication Uri such as: 
     https://westus.api.cognitive.microsoft.com/sts/v1.0/issuetoken
    -->
    <add key="AuthenticationUri" value="" />
  </appSettings>
</configuration>

```


And in the app there are repeated errors - 

![image](https://cloud.githubusercontent.com/assets/5768871/26108750/6a08ea8c-3a1b-11e7-8a2f-1b63751ff5de.png)

**Comment by priyaravi20** [comment]
Hi Bryan - u seem to be posting in the wrong repo. Looks like you are trying to do recognition and not synthesis. I am closing this and please add your comment in the right GitHub repo. You need to send the subscription key  <add key="primaryKey" value=" and not under LuisSUbscriptionkey.

**Comment by bryanjhogan** [comment]
Before closing this, can you point to the right place?

**Comment by priyaravi20** [comment]
https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows - wherever you got the sample code.
