### ISSUE TITLE
401 Auth Error

### ISSUE THREAD

**Issue by friocomohielo** [Azure-Samples/Cognitive-Speech-TTS#47]
Following the directions on 2017-Jun-26, code throws in TTSClient.cs line 119 with web response 401 unauthorized. I do have the Cognitive Services key generated from Azure Portal (generated 1 hour before trying the code) embedded in line 81 of TTSProgram.cs.

**Comment by szhaomsft** [comment]
@friocomohielo   do u still have this issue? 

@v-songl  can do a check

**Comment by boltomli** [comment]
I tried the free [Try](https://azure.microsoft.com/en-us/try/cognitive-services/my-apis/) account, it works well.

```
Bing Speech API

Convert speech to text and back again to understand user intent
5,000 transactions, 20 per minute for each feature.

This API key is currently active
9 days remaining
Endpoint: https://api.cognitive.microsoft.com/sts/v1.0
Key 1: xxx
Key 2: xxx
```
