### ISSUE TITLE
Error while running NodeJS HTTP client example

### ISSUE THREAD

**Issue by cache91** [Azure-Samples/Cognitive-Speech-TTS#48]
Hey , I am getting 2 types of errors.
1. Illegal instruction : 4
2. null < Buffer > 

There is no references to these errors. Can you guys help me ? 
I am using the example file included in the project

**Comment by boltomli** [comment]
Hi, did you get the key for the API? I had a try just now and it works. Did you encounter npm install errors? In addition, if you didn't change the code, you'll need audio device to hear the sound so it might not work well on a remote server or virtual machine.

**Comment by cache91** [comment]
Yes i did get the key. I am using an external speaker.

**Comment by boltomli** [comment]
Hi, I had a few tries in different environments, all is fine. If you run Windows, Python 2 through Anaconda would a good choice to make it work.

**Comment by szhaomsft** [comment]
no more responses
