### ISSUE TITLE
How to get app id and client id for TTS ?

### ISSUE THREAD

**Issue by MADRamesh** [Azure-Samples/Cognitive-Speech-TTS#49]
I have integrated your TTSClient.cs in my mvc project, in localhost it works fine. But i have hosted in our server IIS and generated https:// public url in that text-to-speech is not working.
Is need to generate app id and client id unique for my application ? if so and how do get that ?
please suggest me on this...

**Comment by szhaomsft** [comment]
any error message?

**Comment by MADRamesh** [comment]
no error messages showing...

**Comment by MADRamesh** [comment]
is any one face this issue ?
