### ISSUE TITLE
How to achieve this in javascript.

### ISSUE THREAD

**Issue by MADRamesh** [Azure-Samples/Cognitive-Speech-TTS#51]
i need to do TTS in client side, so is there any source/sample available ?
could someone please help on this.

**Comment by MADRamesh** [comment]
i need to do TTS in client side, so is there any source/sample available ?
could someone please help on this.

**Comment by wolfma61** [comment]
How about these 2 references:
documentation:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjswebsockets

sample:
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript

thx
Wolfgang

**Comment by MADRamesh** [comment]
@wolfma61 
Thanks for your comment. 
In my MVC application i need to integrate TTS in client side without interaction between server (c#). Is there any sample like Speech To Text(https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript) websocket. 

thanks,
Ramesh Kumar M.

**Comment by MADRamesh** [comment]
@wolfma61 
In this sample (https://github.com/Azure-Samples/Cognitive-Speech-TTS/) there is an source in NodeJS i just created the webpack of it and tried to use in my mvc application but its not working.

please help me on this.

thanks,
Ramesh Kumar M.

**Comment by priyaravi20** [comment]
We only have a REST implementation of TTS client and no websocket implementation. https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/CSharp is a csharp implementation of TTS.

**Comment by MADRamesh** [comment]
@priyaravi20 ,
Thanks for your response. Is there any way to achieve in javascript. I have tried the NodeJs sample (generated webpack) but that also not works. 
So could any one please suggest me on this.

Regards,
Ramesh Kumar M.

**Comment by priyaravi20** [comment]
@MADRamesh - What is the error you are seeing using the nodejs sample?

**Comment by boltomli** [comment]
Hi @MADRamesh 
The sample in NodeJS would set output to speaker by default. Did you change that part of code to stream the response to your client side js?

**Comment by MADRamesh** [comment]
I created the webpack using this config 
![image](https://user-images.githubusercontent.com/18552160/30680511-9c052a30-9ebd-11e7-9d06-d7446e6a39e0.png)

Here is the sample,
![image](https://user-images.githubusercontent.com/18552160/30680538-cb6fa4c6-9ebd-11e7-9b6e-a6c2987caa57.png)

i tried to run this sample then i faced this issue,
![image](https://user-images.githubusercontent.com/18552160/30680558-e31ac358-9ebd-11e7-9888-497f77f016cd.png)

**Comment by boltomli** [comment]
It looks like an issue that is in your code? I don't have much experience on webpack, but it should be fine to use this way.

**Comment by MADRamesh** [comment]
@boltomli:
i didn't change any code. just generated the webpack and run the sample which is already in this repository only.
Also the way how i generate the webpack also shared with screenshot(webpack.config.js) here.

**Comment by boltomli** [comment]
I had a try and it works well with webpack and the config. Is `npm i` finished without error? I had to add python 2 to the path.

**Comment by MADRamesh** [comment]
@boltomli:
Webpack generation is successful but if i use the outcome js file in sample then it shows this error.

**Comment by boltomli** [comment]
Do you see the same error if use `npm i` then `node TTSSample.js` without building webpack?

**Comment by MADRamesh** [comment]
@boltomli:
Without building webpack it works fine.

**Comment by boltomli** [comment]
OK, cool. It's the same to me. So what about trying to update webpack or try some other way? Since it works well directly, it should not be a sample or service issue. Also, webpack 3.6.0 works fine to me `npm i -g webpack`

**Comment by MADRamesh** [comment]
@boltomli:
here is an client side library for text to speech 
https://github.com/davrous/BingSpeech
but it doesn't support in IE browser alone
