### ISSUE TITLE
Could not load file or assembly Bond.IO, Version=1.0.0.0...

### ISSUE THREAD

**Issue by mrctito** [Azure-Samples/Cognitive-Speech-TTS#52]
Dear sirs,

I´am trying to use Bing Speech library service to translate speech to text in my ChatBot, but this error happens in method "RecognizeAsync" of class "SpeechClient".

Could not load file or assembly Bond.IO, Version=1.0.0.0, ... or one of its dependencies. The located assembly manifest definition does not match the assembly reference.

All nuget packages are up to date, as is my Visual Studio 2017 Enterprise.

Thank you for any help.

**Comment by priyaravi20** [comment]
Are you using the Speech recognition library. This is a Text To speech Forum. Please clarify exactly which SDK you are using and file the request in the right forum.
