### ISSUE TITLE
TTSService.Synthesize takes a long time to return

### ISSUE THREAD

**Issue by christianmontecino** [Azure-Samples/Cognitive-Speech-TTS#53]
Hi. I am using Java to call TTSService.Synthesize. For some reason takes a long time for the service to come back with the MP3.  What AudioOutputFormat should I use to make the smallest mp3 and hopefully stream it to the client?

Thanks.

Chris

**Comment by boltomli** [comment]
@neoguo0601 do you have any idea?

**Comment by neoguo0601** [comment]
If you only use MP3 format, audio-16khz-32kbitrate-mono-mp3 is the smallest. 
You can browse this link to get more format,
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech/api-reference-rest/bingvoiceoutput#SupLocales

In fact, we support streaming.  You can modify the TTSService.java 88~90 lines break the while to get it. 

Thanks

**Comment by christianmontecino** [comment]
Hi. Can you please help with this issue? The files created are too big and I can't seem to get that Audioformat to work....The web service returns an exception. Please see below.

Can you suggest how to get streaming to work with the smallest size possible?

Error:

Current Date: 20170927-090725
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input str
eam from input file
        at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:
1189)
        at com.audio.service.TTSSample.main(TTSSample.java:105)

Thanks!

Christian

**Comment by neoguo0601** [comment]
Can you put out your code of TTSSample.java?

**Comment by christianmontecino** [comment]
Here you go.
The AudioFormat you suggested does not work for some reason and the service does not stream.
Thanks for your help!
Regards,
Christian
