### ISSUE TITLE
how can we add header values to the ssml being generated

### ISSUE THREAD

**Issue by ramicodes** [Azure-Samples/Cognitive-Speech-TTS#54]
In the code you are using: GenerateSsml(inputOptions.Locale, genderValue, inputOptions.VoiceName, inputOptions.Text) to generate the SSML.
How can we add SSML tags to change the voice output via SSML, like speaking rate, pronunciation etc?
Thanks

**Comment by boltomli** [comment]
Hi there, the tags can be created as indicated in SSML standard and enclosed in the text. Feel free to have a try.
