### ISSUE TITLE
How know when the speak is finished?

### ISSUE THREAD

**Issue by seransaca** [Azure-Samples/Cognitive-Speech-TTS#55]
Hi!

Congratulation, but I have one questions.

How do I know when the Synthesizer is finished? For example, when the Synthesizer finish, I change to other app,

It needs to know when Synthesizer is DONE/FINISHED to run another things.

Thanks

**Comment by neoguo0601** [comment]
All the requests are in line with the HTTP protocol, we can get Http state to determine whether the completion of synthesis

thanks

**Comment by seransaca** [comment]
I mean when you run the speak, how do I know what it takes to say the text that has been passed to speak?

**Comment by radhasoni65** [comment]
hey @neoguo0601  can you please let me know where i have to know the audio is stop after finishing play.
i am working in an project and at every stage i have to change the UI of Applicationo please help me...

**Comment by boltomli** [comment]
It depends on your project. Close for now.
