### ISSUE TITLE
License of output audio?

### ISSUE THREAD

**Issue by avimar** [Azure-Samples/Cognitive-Speech-TTS#56]
Amazon Polly [FAQ ](https://aws.amazon.com/polly/faqs/) says that you are allowed unlimited re-use.

>Q. Can I use the service for generating static voice prompts that will be replayed multiple times?
>Yes, you can. The service does not restrict this and there are no additional costs for doing so.

I can't find a similar clause for the Bing TTS offering. For my own commercial use, I expect it's allowed.

However, I would like to generate prompts for FreeSWITCH and distribute it (general project is under MPL 1.1) and I'm sure we should have an official notice of what license, if any, covers the the generated audio files.

Thanks!

**Comment by priyaravi20** [comment]
You can use the attribution requirements as a guidance in the service terms https://azure.microsoft.com/en-us/support/legal/cognitive-services-terms/
