### ISSUE TITLE
TTS Example works fine in emulator but not able to play the audio from webchat when deployed in azure

### ISSUE THREAD

**Issue by anurag1234567** [Azure-Samples/Cognitive-Speech-TTS#59]
TTS Example works fine in emulator but not able to play the audio from webchat when deployed in azure.

**Comment by boltomli** [comment]
Which format does webchat support? You might try MP3. See the formats listed on https://docs.microsoft.com/en-us/azure/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput
