### ISSUE TITLE
Python TTSample outputs 403 forbidden

### ISSUE THREAD

**Issue by vkucalo** [Azure-Samples/Cognitive-Speech-TTS#61]
After filling in the API-key required by the [Python TTS](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/Python) I acquire the access token, however the POST request that follows outputs a 403 forbidden.

**Comment by boltomli** [comment]
I registered a new account and tried. Cannot reproduce the error. Perhaps try again some time? Close for now and let us know if any further information.
