### ISSUE TITLE
Failed to load https://speech.platform.bing.com/synthesize

### ISSUE THREAD

**Issue by phonga3cvp** [Azure-Samples/Cognitive-Speech-TTS#63]
When I make a http request to https://speech.platform.bing.com/synthesize, the server response 204 with error message 'Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:58231' is therefore not allowed access.' How can i solve this problem?

**Comment by boltomli** [comment]
I don't know your overall design, but guess you can just add the header to request to try.

**Comment by xiwangjiang** [comment]
have you fixed your problem?
