### ISSUE TITLE
Confidence

### ISSUE THREAD

**Issue by zallia2** [Azure-Samples/Cognitive-Speech-TTS#65]
Hi what is the general rule of thumb for the confidence in Microsoft Cognitive Services? Do you have any graph or anything available which states if it is less than 50% don't trust the results and if it is above 50% do trust the results. Like also if it is 90%+ it is extremely accurate results etc.

**Comment by boltomli** [comment]
I don't think there's a confidence level suitable for TTS part of speech services. Perhaps you are checking SR or LU?
