### ISSUE TITLE
What are X-Search-AppId and X-Search-ClientID?

### ISSUE THREAD

**Issue by luongvo** [Azure-Samples/Cognitive-Speech-TTS#66]
I would like to integrate Azure TTS into my project but I can run sample project only with demo API key. When using this sdk into real project with subscribed API key, the API always return 403. I dived deep into sdk project and see these values, so where is it from and how to get them?

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/33330ccedadb4baf343ba18fe3149106c9c6f0b1/Android/Sample/speechsdk/src/main/java/com/microsoft/speech/tts/TtsServiceClient.java#L76
https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/33330ccedadb4baf343ba18fe3149106c9c6f0b1/Android/Sample/speechsdk/src/main/java/com/microsoft/speech/tts/TtsServiceClient.java#L77

**Comment by punitganshani** [comment]
+1

**Comment by luongvo** [comment]
@punitganshani where are they?

**Comment by punitganshani** [comment]
Here's the link - 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoiceoutput#Http

Do remember that the IDs should **not** have dashes

**Comment by luongvo** [comment]
@punitganshani I know it before, my concern is is it created from somewhere like a generated id in azure app or create by own. What happens if these ids are duplicated between apps when calling to cognitive services api and how can we avoid that duplicated issue?

**Comment by szhaomsft** [comment]
yes, these fields are optional.

**Comment by NinoSkopac** [comment]
Then, I think, they should be removed from the sample.
