### ISSUE TITLE
Quick link for paid tier not working?

### ISSUE THREAD

**Issue by boltomli** [Azure-Samples/Cognitive-Speech-TTS#68]
https://portal.azure.com/#create/Microsoft.CognitiveServices/apitype/Bing.Speech/pricingtier/S0

It shows:

Oops!

Could not create the marketplace item

This marketplace item is not available.

**Comment by boltomli** [comment]
PR #72 addresses this link issue

**Comment by boltomli** [comment]
PR #71 resolved this.

**Comment by MrKnowChu** [comment]
Could you share how you resolved this?

**Comment by boltomli** [comment]
The link is changed to <https://go.microsoft.com/fwlink/?LinkId=872236>
