### ISSUE TITLE
no voice is heard 

### ISSUE THREAD

**Issue by zinebElHilali** [Azure-Samples/Cognitive-Speech-TTS#75]
after running the python code there is no voice heard and no errors
********************************************output*****************
Connect to server to get the Access Token
200 OK
Access Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJleHAiOiIxNTI3NDQ4ODIyIiwicmVnaW9uIjoid2VzdHVzIiwic3Vic2NyaXB0aW9uLWlkIjoiMzM1YmNhOGU4MGMzNGVhOThlZGUwYTBmNDNkNmQ4ZjciLCJwcm9kdWN0LWlkIjoiU3BlZWNoU2VydmljZXMuRnJlZSIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJzY29wZSI6InNwZWVjaHNlcnZpY2VzIiwiYXVkIjoidXJuOm1zLnNwZWVjaHNlcnZpY2VzLndlc3R1cyJ9.TaNVftHAYkF1Ouw2EB_ALJRAX5IJfC65E9ejx_KHL9c

Connect to server to synthesize the wave
200 OK
The synthesized wave length: 212934

Process finished with exit code 0

**Comment by boltomli** [comment]
Since you had a wave length of about 200k data, it was successful. The sample code doesn't do anything with the data, anyway. You can make use of the data in your application, for example, play back directly, save to file, stream to service, etc.

**Comment by Onotseike** [comment]
How do play directly in python? or save to file?

**Comment by newnewcoder** [comment]
You can simply save file like below:

~~~python
with open('data.wav', 'wb') as f:
    f.write(data)
~~~

and play it by using `pydub`

~~~python
from pydub import AudioSegment
from pydub.playback import play
sound = AudioSegment.from_wav('data.wav')
play(sound)
~~~

ref: https://pythonbasics.org/python-play-sound/#pydub
