### ISSUE TITLE
TTS not working on Azure hosting

### ISSUE THREAD

**Issue by mukeshmishra996** [Azure-Samples/Cognitive-Speech-TTS#78]
I have created an ASP .Net MVC App and I implemented C# TTS example to my application. TTS working fine when my application running on the local machine. But after deploying applications on Azure environment It's stopped working. Can anybody help me to find the solution. Any other way to implement TTS in ASP .NET MVC App.

**Comment by szhaomsft** [comment]
can u share more details?
