### ISSUE TITLE
All of my API keys failed.

### ISSUE THREAD

**Issue by axzxc1236** [Azure-Samples/Cognitive-Speech-TTS#79]
It used to work fine a month ago, but I ran the same program and get error today.

I've tried:

1. Create new keys to test if it works.

2. Use Node.js and C# example.

I still get error messages running examples

There is "List keys" in Azure activity log every time I run my program.

It looks like any key I created is now invalid.

C# sample error message:

```
Starting Authtentication
Token: eyJhbGciOiJodHRwOi8vd3d3Lncz......(Token)

Starting TTSSample request code execution.
Response status code: [Unauthorized]
Unable to complete the TTS request: [CognitiveServicesTTS.GenericEventArgs`1[System.Exception]]

```

Node.js sample error message:
`null '{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }'`
(Note that I am using new created keys and still get this message.)

**Comment by axzxc1236** [comment]
I just changed endpoints and it works now. (Appearently endpoints changed.)

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/NodeJS/TTSService.js#L33
Change that to "https://api.cognitive.microsoft.com/sts/v1.0/issueToken"

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/NodeJS/TTSService.js#L43
Change that to "https://speech.platform.bing.com/synthesize"

**Comment by boltomli** [comment]
Yes, the endpoints you used are the legacy ones. If you have the old key you need those. Glad to see you figured it out :)
