### ISSUE TITLE
[Node.js] Program stops running after Synthesize() is completed, how to stop this behavior?

### ISSUE THREAD

**Issue by axzxc1236** [Azure-Samples/Cognitive-Speech-TTS#80]
This is my current [code](https://gist.github.com/axzxc1236/c1273dcff4d4ec4de3b655fb0894f618), what I want the program to say is passed through Socket.io connection, but the program stopped working after spoken first sentence, and I have no clue what caused the program to stop.

**Comment by axzxc1236** [comment]
hmm.... I wanted to do step-by step debug using "node inspect", but the script somehow bypassed it.

**Comment by axzxc1236** [comment]
I tried to do step-by step debug, but I still don't know what's wrong.

```
break in internal/process/next_tick.js:180
 178         // callback invocation with small numbers of arguments to avoid the
 179         // performance hit associated with using `fn.apply()`
>180         _combinedTickCallback(args, callback);
 181
 182         emitAfter(tock[async_id_symbol]);
debug>
debug> There was an internal error in node-inspect. Please report this bug.
read ECONNRESET
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
```

**Comment by axzxc1236** [comment]
I tried to run the script with [node-supervisor](https://github.com/petruisfan/node-supervisor), and I get this message after it crashes:
`Program node index.js exited with code 3221226356'

**Comment by szhaomsft** [comment]
Is this still an issue?  

@v-songl
