### ISSUE TITLE
wave length =0 

### ISSUE THREAD

**Issue by LulwahAlshuqair** [Azure-Samples/Cognitive-Speech-TTS#96]
Hi, i'm using the Android/java code but it is not working. 

first, when i debug it shows that the wave length is 0 which indicate that there's no sound but how can i solve this problem?

Also, the Synthesizer class method `public byte[] SpeakSSML(String ssml)` the result array is always returned with null value. Last, in the same method there's this comment "* check current network environment * to do... " does this mean i need to write some code in here or what? because the readme file doesn't say anything about this 

Thank you very much

**Comment by szhaomsft** [comment]
you can now use speech SDK for TTS which has android sample 

https://github.com/Azure-Samples/cognitive-services-speech-sdk
