### ISSUE TITLE
Audio not playing. file appear to be corrupted

### ISSUE THREAD

**Issue by donniekerr** [Azure-Samples/Cognitive-Speech-TTS#98]
I'm running this example inside of an Azure Function.  I added code to write the response to Azure blob storage. 
The resulting audio mp3 does not play in browser or opening it directly in QuickTime.
I take the output and create a ReadStream from it, then save that to blob storage.  I've tries various audio formats and none work. 

Can you please tell me what I'm doing wrong?  I can't get an answer here
https://social.msdn.microsoft.com/Forums/en-US/b1b9b5bd-6f74-464e-86a4-d1493b2c7c23/texttospeech-audio-playback-solution?forum=AzureCognitiveService 

Thank you,
Donnie

[https://sandyspeaksstorage.blob.core.windows.net/sandy-speaks/e5f3613d-31f1-41f5-beba-08443ec7aa17.mp3

](https://sandyspeaksstorage.blob.core.windows.net/sandy-speaks/e5f3613d-31f1-41f5-beba-08443ec7aa17.mp3

)
`
module.exports = function(context, req) {

const xmlbuilder = require('xmlbuilder');
const request = require('request');
const fs = require('fs');
const {
  Aborter,
  BlobURL,
  BlockBlobURL,
  ContainerURL,
  ServiceURL,
  StorageURL,
  SharedKeyCredential,
  uploadStreamToBlockBlob
} = require("@azure/storage-blob");
const account = "myaccount";
const accountKey = "==";
const sharedKeyCredential = new SharedKeyCredential(account, accountKey);
const pipeline = StorageURL.newPipeline(sharedKeyCredential);
const serviceURL = new ServiceURL(`https://${account}.blob.core.windows.net`,pipeline);
const containerName = `sandy-speaks`;
const containerURL = ContainerURL.fromServiceURL(serviceURL, containerName);
const subscriptionKey = "xxxx" ;

let text = req.body.text; //from http request

function textToSpeech(subscriptionKey, saveAudio) {
    let options = {
        method: 'POST',
        uri: 'https://eastus.api.cognitive.microsoft.com/sts/v1.0/issueToken',
        headers: {
            'Ocp-Apim-Subscription-Key': subscriptionKey
        }
    };
    
    function getToken(error, response, body) {
        context.log("Getting your token...\n")
        if (!error && response.statusCode == 200) {
            
            saveAudio(body)
        }
        else {
          context.log(error);
        }
    }
    request(options, getToken)
}

function saveAudio(accessToken) {
   
    let xml_body = xmlbuilder.create('speak')
      .att('version', '1.0')
      .att('xml:lang', 'en-us')
      .ele('voice')
      .att('xml:lang', 'en-us')
      .att('name', 'Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)')
      .txt(text)
      .end();
   
    let body = xml_body.toString();

    let options = {
        method: 'POST',
        baseUrl: 'https://eastus.tts.speech.microsoft.com/',
        url: 'cognitiveservices/v1',
        headers: {
            'Authorization': 'Bearer ' + accessToken,
            'cache-control': 'no-cache',
            'User-Agent': 'tts',
            'X-Microsoft-OutputFormat': 'audio-24khz-48kbitrate-mono-mp3',
            'Content-Type': 'application/ssml+xml'
        },
        body: body
    };
    
    function convertText(error, response,body){
     context.log(JSON.stringify(body))
      if (!error && response.statusCode == 200) {
        context.log("Converting text-to-speech. Please hold...\n")
      }
      else {
        context.log(error);
      }
      context.log("Your file is ready.\n")
      
      //save to blob storage
         const uuidv4 = require('uuid/v4'); 
        let filename = uuidv4()+'.mp3';
        context.log(filename)
        const blobName = filename;
        const fileBuffer = body;
        const blobURL = BlobURL.fromContainerURL(containerURL, blobName);
        context.log(blobURL)
        const blockBlobURL = BlockBlobURL.fromBlobURL(blobURL);
        const Stream = require('stream')
        const readableStream = new Stream.Readable()
        readableStream._read = () => {} 
        readableStream.push(fileBuffer)
        readableStream.push(null)
      
        uploadStreamToBlockBlob(
            Aborter.timeout(30 * 60 * 60 * 1000), 
            readableStream,
            blockBlobURL,
            4 * 1024 * 1024,
            20,
            {
            progress: ev => context.log(ev)
            }
          );
          context.log("uploadStreamToBlockBlob success");  
      //end save to blob storage
      context.done(null,{res:blobURL})
      
    }
    
  request(options, convertText);
    
}

textToSpeech(subscriptionKey, saveAudio);

}
`

**Comment by boltomli** [comment]
Hi Donnie, thanks for the details. The .mp3 file you saved to blob seems to be a combination of multiple tries. Did you try save the audios to local one by one and listen?

**Comment by donniekerr** [comment]
@boltomli , I don't understand what you mean by a combination of tries?  How is that possible if each http request makes a separate TTS api call and creates a new unique mp3 file with unique file name each time?

**Comment by boltomli** [comment]
Yes, I think you need to create and save a unique file each time. Or delete the previous one/rewrite.

**Comment by donniekerr** [comment]
This line
let filename = uuidv4()+'.mp3';
generates a unique file name each time before saving to storage. see the test files created each time the function runs ...
<img width="671" alt="screenshot 2019-02-19 at 9 35 39 pm" src="https://user-images.githubusercontent.com/41065378/53064691-5ce4a700-348e-11e9-8ea6-9579073ed28a.png">

**Comment by donniekerr** [comment]
How can you tell the file contains a combination?

**Comment by boltomli** [comment]
@xiaozhouz Do you have any idea?

**Comment by szhaomsft** [comment]
do you flush the stream?

make sure doing that

or can u reproduce with the C# demo?

**Comment by szhaomsft** [comment]
no activities

**Comment by vaibhavtekam** [comment]
Were you able to get it working? I seem to be facing the same issue. 
Any help will be appreciated. 
When I check the duration it shows 0.0 seconds, file size is around 300+ kb.

**Comment by szhaomsft** [comment]
@vaibhavtekam  what is your code? do you use the C# demo to try?

**Comment by szhaomsft** [comment]
@vaibhavtekam  it seems the original issue is solved here

https://social.msdn.microsoft.com/Forums/en-US/b1b9b5bd-6f74-464e-86a4-d1493b2c7c23/texttospeech-audio-playback-solution?forum=AzureCognitiveService

**Comment by vaibhavtekam** [comment]
Yes, that's right. That code helped. 
Thanks @szhaomsft
