### ISSUE TITLE
NodeJS : converting stream to bytes

### ISSUE THREAD

**Issue by MissRedfreak** [Azure-Samples/Cognitive-Speech-TTS#99]
Hello,
I would like to use TTS without saving the file in .wav.
I'm trying the record it in bytes (I'm using other services, this would help me).

I've done a bit of research...with no luck (I'm fairly new to NodeJs to be fair).

Could  somebody explain to me how I could simply gather the result of the request, as byte array (returning it or as a new variable) please?

The code I have is just the copy of the quickstart :)

Thank you in advance !

**Comment by boltomli** [comment]
Hi, I'm not an expert on JavaScript and not sure about your actual usage, but it seems not part of the speech services issue. Can you take a look at an earlier version of the sample in case?

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/cf7f2136bef8968bbfe72559438650370b7765fd/Samples-Http/NodeJS/TTSService.js
